#!/usr/bin/env python3
"""Data for batch quote/thinker generation."""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# -----------------------------------------------------------------------------
# New thinker entries to create
# -----------------------------------------------------------------------------
NEW_THINKERS = {
    "paul-feyerabend": {
        "path": "哲学/学派/科学哲学/费耶阿本德.md",
        "title": "保罗·费耶阿本德 · Paul Feyerabend",
        "domain": "哲学",
        "school": "philosophy-of-science",
        "era": "contemporary",
        "birth": 1924,
        "death": 1994,
        "nationality": "奥地利-美国",
        "tags": ["philosophy-of-science", "epistemological-anarchism", "scientific-pluralism"],
        "aliases": ["费耶阿本德", "Paul Feyerabend"],
        "intro": "保罗·费耶阿本德（Paul Feyerabend，1924–1994）是奥地利裔科学哲学家，以“怎么都行”的旗手闻名。他反对将科学方法单一化，主张认识论无政府主义，强调神话、巫术与现代科学在认知上的平等地位。",
        "theses": [
            ("认识论无政府主义", "不存在唯一正确的科学方法。任何方法论规则都有反例，科学进步往往依赖于反规则的即兴操作，如哥白尼革命与伽利略的修辞策略。"),
            ("科学与其他传统的平等", "科学与神话、宗教、巫术并非理性与非理性的对立。它们都是人类应对世界的方式，科学的特殊地位是一种社会建构，而非认识论特权。"),
            ("理论增生与可证伪性的局限", "单一理论与多元理论竞争时，后者更能暴露前者的隐藏假设。科学进步需要“怎么都行”的宽容，而不是波普尔式证伪的独断。"),
        ],
        "works": [
            "*Against Method: Outline of an Anarchistic Theory of Knowledge* (1975)",
            "*Science in a Free Society* (1978)",
            "*Farewell to Reason* (1987)",
        ],
        "links": [
            "与 [卡尔·波普尔](../分析哲学/波普尔.md) 共享对科学哲学的关注，但反对其方法论的规范性。",
            "与 [托马斯·库恩](../分析哲学/库恩.md) 共同挑战逻辑实证主义，但费耶阿本德更激进地否定一切方法规则。",
        ],
        "reading": [
            "Feyerabend, P. *Against Method* (1975)",
            "Preston, J. *Feyerabend: Philosophy, Science and Society* (1997)",
        ],
    },
    "john-austin": {
        "path": "哲学/学派/分析哲学/奥斯汀.md",
        "title": "约翰·奥斯汀 · J. L. Austin",
        "domain": "哲学",
        "school": "analytic-philosophy",
        "era": "contemporary",
        "birth": 1911,
        "death": 1960,
        "nationality": "英国",
        "tags": ["philosophy-of-language", "speech-acts", "ordinary-language-philosophy"],
        "aliases": ["奥斯汀", "J. L. Austin", "约翰·奥斯汀"],
        "intro": "约翰·兰肖·奥斯汀（J. L. Austin，1911–1960）是英国语言哲学家，日常语言学派代表。他提出“言语行为理论”，指出说话不只是描述世界，也是在施行行动。",
        "theses": [
            ("言语即行为", "说出一句合适的话本身就是一种行为。例如“我道歉”“我命名这艘船”不只是陈述，而是在完成道歉或命名这一行为。"),
            ("言内、言外与言后行为", "言内行为是说出有意义的话语；言外行为是话语所执行的特定功能（承诺、命令、请求）；言后行为是话语对听者产生的实际效果。"),
            ("记述话语与施行话语", "并非所有语句都是真值可判断的记述。许多语句的价值在于是否“合适地”完成某种社会行为，而非是否符合事实。"),
        ],
        "works": [
            "*How to Do Things with Words* (1962)",
            "*Sense and Sensibilia* (1962)",
        ],
        "links": [
            "与 [路德维希·维特根斯坦](维特根斯坦.md) 共同奠定日常语言哲学，但奥斯汀更注重语言的细微分类。",
            "与 [约翰·塞尔](../分析哲学/约翰.md) 形成直接的师生与批评关系，塞尔发展了奥斯汀的言语行为理论。",
        ],
        "reading": [
            "Austin, J. L. *How to Do Things with Words* (1962)",
            "Searle, J. *Speech Acts: An Essay in the Philosophy of Language* (1969)",
        ],
    },
    "jacques-ellul": {
        "path": "哲学/学派/技术哲学/艾吕尔.md",
        "title": "雅克·艾吕尔 · Jacques Ellul",
        "domain": "哲学",
        "school": "philosophy-of-technology",
        "era": "contemporary",
        "birth": 1912,
        "death": 1994,
        "nationality": "法国",
        "tags": ["philosophy-of-technology", "technique", "propaganda", "christian-anarchism"],
        "aliases": ["艾吕尔", "Jacques Ellul", "雅克·艾吕尔"],
        "intro": "雅克·艾吕尔（Jacques Ellul，1912–1994）是法国社会学家、法学家与神学家。他以“技术社会”批判著称，指出“技术”（la technique）已成为自主的、追求效率至上的总体系统，深刻塑造了现代生活的各个领域。",
        "theses": [
            ("技术作为自主系统", "技术不是中性的工具集合，而是一种自我增长的逻辑：凡事追求效率、标准化与可计算。这一逻辑逐渐渗透经济、政治、法律与伦理。"),
            ("手段对目的的倒置", "在技术社会中，手段不再服务于明确的目的；相反，效率本身成为最高目的，人则被改造为适应技术系统的环节。"),
            ("宣传的技术基础", "现代宣传之所以有效，不仅因为意识形态，更因为它借助技术手段（媒体、数据、心理学）将个体嵌入一个看似自然的社会环境。"),
        ],
        "works": [
            "*La Technique ou l'Enjeu du siècle* (1954)",
            "*Propagandes* (1962)",
            "*The Technological Society* (1964, English)",
        ],
        "links": [
            "与 [马丁·海德格尔](../存在主义/海德格尔/README.md) 共同追问技术的本质，但艾吕尔更强调技术系统的社会自主性。",
            "与 [赫伯特·马尔库塞](../../../伦理政治/学派/批判理论/赫伯特.md) 共享对单向度社会的批判。",
        ],
        "reading": [
            "Ellul, J. *The Technological Society* (1964)",
            "Ellul, J. *Propaganda: The Formation of Men's Attitudes* (1965)",
        ],
    },
    "harry-braverman": {
        "path": "社会学/学派/劳动研究/布雷弗曼.md",
        "title": "哈里·布雷弗曼 · Harry Braverman",
        "domain": "社会学",
        "school": "labor-studies",
        "era": "contemporary",
        "birth": 1920,
        "death": 1976,
        "nationality": "美国",
        "tags": ["labor-process", "deskilling", "monopoly-capitalism", "marxism"],
        "aliases": ["布雷弗曼", "Harry Braverman"],
        "intro": "哈里·布雷弗曼（Harry Braverman，1920–1976）是美国马克思主义社会学家与工人运动活动家。他在《劳动与垄断资本》中系统分析了资本主义劳动过程中的“去技能化”趋势，成为劳动过程理论的奠基之作。",
        "theses": [
            ("劳动过程的去技能化", "资本家为了控制劳动过程，倾向于将工人的知识转移到管理方与机器中，使劳动碎片化、标准化，从而削弱工人的议价能力。"),
            ("概念与执行的分离", "当设计、规划与实际操作被拆分时，工人失去对工作整体的理解与控制权；知识被垄断，劳动变得单调。"),
            ("垄断资本与劳动转型", "在垄断资本主义阶段，科学技术与管理技术成为控制劳动的新工具，去技能化从手工劳动扩展到白领与服务业。"),
        ],
        "works": [
            "*Labor and Monopoly Capital: The Degradation of Work in the Twentieth Century* (1974)",
        ],
        "links": [
            "与 [卡尔·马克思](../古典社会学/马克思/README.md) 的剩余价值理论直接相承，布雷弗曼将其具体化为劳动过程分析。",
            "与 [大卫·格雷伯](格雷伯.md) 后来的“狗屁工作”论述形成对话：去技能化与无意义劳动共同构成当代工作的批判维度。",
        ],
        "reading": [
            "Braverman, H. *Labor and Monopoly Capital* (1974)",
            "Burawoy, M. *Manufacturing Consent* (1979)",
        ],
    },
    "david-graeber": {
        "path": "社会学/学派/劳动研究/格雷伯.md",
        "title": "大卫·格雷伯 · David Graeber",
        "domain": "社会学",
        "school": "labor-studies",
        "era": "contemporary",
        "birth": 1961,
        "death": 2020,
        "nationality": "美国",
        "tags": ["anthropology", "bullshit-jobs", "debt", "anarchism", "labor"],
        "aliases": ["格雷伯", "David Graeber", "大卫·格雷伯"],
        "intro": "大卫·格雷伯（David Graeber，1961–2020）是美国人类学家与社会活动家，以“占领华尔街”运动与《狗屁工作》《债：第一个5000年》闻名。他将无政府主义实践与人类学视角结合，重新审视劳动、债务与社会制度。",
        "theses": [
            ("狗屁工作的蔓延", "大量现代工作缺乏社会价值，却被包装成有意义。人们从事这些工作不是因为社会需要，而是因为制度性的支配与雇佣关系。"),
            ("护理劳动的贬值", "真正创造关怀、教育、养育价值的工作往往报酬最低、最不被尊重；这与资本主义对“生产力”的狭隘定义有关。"),
            ("债务作为社会权力", "债务不仅是经济关系，更是道德与政治控制工具。它让负债者感到羞耻与义务，从而维系不平等结构。"),
        ],
        "works": [
            "*Debt: The First 5,000 Years* (2011)",
            "*The Democracy Project* (2013)",
            "*Bullshit Jobs: A Theory* (2018)",
        ],
        "links": [
            "与 [卡尔·马克思](../古典社会学/马克思/README.md) 的劳动批判形成跨时代对话，但格雷伯更关注“无意义工作”而非剥削。",
            "与 [哈里·布雷弗曼](布雷弗曼.md) 共同追问资本主义如何贬低劳动的意义与技能。",
        ],
        "reading": [
            "Graeber, D. *Bullshit Jobs* (2018)",
            "Graeber, D. *Debt: The First 5,000 Years* (2011)",
        ],
    },
    "frank-pasquale": {
        "path": "社会学/学派/算法社会/帕斯奎尔.md",
        "title": "弗兰克·帕斯奎尔 · Frank Pasquale",
        "domain": "社会学",
        "school": "algorithmic-society",
        "era": "contemporary",
        "birth": 1974,
        "nationality": "美国",
        "tags": ["algorithmic-accountability", "black-box-society", "law", "technology-policy"],
        "aliases": ["帕斯奎尔", "Frank Pasquale"],
        "intro": "弗兰克·帕斯奎尔（Frank Pasquale，1974– ）是美国法律学者，研究算法、人工智能与法律监管的交叉领域。他在《黑箱社会》中揭示评分、搜索与算法决策如何重塑权力与责任。",
        "theses": [
            ("黑箱社会的三重问题", "搜索、评分与决策系统的不透明性，导致信息不对称、不公平竞争与个人权利受损。"),
            ("算法问责的必要性", "法律不能止步于“技术中立”的幻想，而应要求算法系统具备可解释性、可审计性与救济渠道。"),
            ("平台权力与公共治理", "大型平台既像公权力又像私人企业，需要新的监管框架来平衡创新与公共利益。"),
        ],
        "works": [
            "*The Black Box Society: The Secret Algorithms That Control Money and Information* (2015)",
            "*New Laws of Robotics: Defending Human Expertise in the Age of AI* (2020)",
        ],
        "links": [
            "与 [肖沙娜·祖博夫](../网络社会/肖沙娜.md) 共同批判数字资本主义的权力形式，帕斯奎尔侧重法律与算法问责。",
            "与 [凯西·奥尼尔](奥尼尔.md) 都关注算法对社会不公的放大效应。",
        ],
        "reading": [
            "Pasquale, F. *The Black Box Society* (2015)",
            "Pasquale, F. *New Laws of Robotics* (2020)",
        ],
    },
    "cathy-oneil": {
        "path": "社会学/学派/算法社会/奥尼尔.md",
        "title": "凯西·奥尼尔 · Cathy O'Neil",
        "domain": "社会学",
        "school": "algorithmic-society",
        "era": "contemporary",
        "birth": 1972,
        "nationality": "美国",
        "tags": ["algorithmic-bias", "data-science", "weapons-of-math-destruction", "fairness"],
        "aliases": ["奥尼尔", "Cathy O'Neil", "凯西·奥尼尔"],
        "intro": "凯西·奥尼尔（Cathy O'Neil，1972– ）是美国数学家、数据科学家与作家。她在《数学杀伤性武器》中揭示大数据模型如何以“客观”之名固化偏见、放大不平等。",
        "theses": [
            ("数学模型的道德政治性", "算法与统计模型并非中立工具，它们嵌入设计者的目标、数据的历史偏见与权力的运作逻辑。"),
            ("伤害的可扩展性", "当模型被大规模应用于招聘、信贷、警务与教学时，即使微小的偏见也会被系统性放大，形成“数学杀伤性武器”。"),
            ("可解释性与反馈循环", "不透明的模型会自我强化：对贫困社区的预测性警务增加逮捕记录，又“证明”社区更危险，形成闭环歧视。"),
        ],
        "works": [
            "*Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy* (2016)",
            "*The Shame Machine: Who Profits in the New Age of Humiliation* (2022)",
        ],
        "links": [
            "与 [弗兰克·帕斯奎尔](帕斯奎尔.md) 共同呼吁算法问责与监管。",
            "与 [肖沙娜·祖博夫](../网络社会/肖沙娜.md) 的监控资本主义批判形成互补：奥尼尔聚焦模型，祖博夫聚焦数据提取。",
        ],
        "reading": [
            "O'Neil, C. *Weapons of Math Destruction* (2016)",
            "Benjamin, R. *Race After Technology* (2019)",
        ],
    },
    "elaine-scarry": {
        "path": "哲学/学派/政治哲学/斯卡里.md",
        "title": "伊莱恩·斯卡里 · Elaine Scarry",
        "domain": "哲学",
        "school": "political-philosophy",
        "era": "contemporary",
        "birth": 1946,
        "nationality": "美国",
        "tags": ["political-philosophy", "pain", "embodiment", "literature", "violence"],
        "aliases": ["斯卡里", "Elaine Scarry"],
        "intro": "伊莱恩·斯卡里（Elaine Scarry，1946– ）是美国政治哲学家与文学理论家，哈佛大学教授。她在《苦痛中的身体》中分析疼痛如何摧毁语言与世界，并探讨身体与政治暴力的关系。",
        "theses": [
            ("疼痛的不可通约性", "极度疼痛会瓦解个体与世界的关联，使对象消失、语言失效。痛苦具有“去世界化”的力量。"),
            ("身体作为创造与伤害的场域", "人类通过身体创造世界（劳动、想象），也通过身体承受伤害。政治暴力往往以摧毁他人身体为手段。"),
            ("美与公正的关联", "在《论美与 Being Just》中，斯卡里认为对美的关注能够培养一种公平的注意力，引导人走出自我中心。"),
        ],
        "works": [
            "*The Body in Pain: The Making and Unmaking of the World* (1985)",
            "*On Beauty and Being Just* (1999)",
        ],
        "links": [
            "与 [朱迪斯·巴特勒](../../../社会学/学派/性别研究/butler.md) 共同关注脆弱性、身体与政治暴力的关系。",
            "与 [莫里斯·梅洛-庞蒂](../现象学/梅洛庞蒂.md) 的身体现象学形成对话，但斯卡里更强调疼痛的破坏性。",
        ],
        "reading": [
            "Scarry, E. *The Body in Pain* (1985)",
            "Scarry, E. *On Beauty and Being Just* (1999)",
        ],
    },
    "iris-young": {
        "path": "哲学/学派/女性主义/扬.md",
        "title": "艾里斯·马里恩·扬 · Iris Marion Young",
        "domain": "哲学",
        "school": "feminist-philosophy",
        "era": "contemporary",
        "birth": 1949,
        "death": 2006,
        "nationality": "美国",
        "tags": ["feminist-theory", "political-philosophy", "embodiment", "social-justice"],
        "aliases": ["扬", "Iris Marion Young", "艾里斯·扬"],
        "intro": "艾里斯·马里恩·扬（Iris Marion Young，1949–2006）是美国政治哲学家与女性主义理论家。她以“像女孩那样投掷”等分析闻名，揭示女性身体如何被规训，并将“结构性不公”概念引入政治哲学。",
        "theses": [
            ("像女孩那样投掷", "女性常被训练以限制性的方式使用身体，这不仅是生理差异，更是性别规范的具身化结果。"),
            ("压迫的五张面孔", "压迫不能仅归结为个别压迫者；它通过剥削、边缘化、无权、文化帝国主义与暴力五种结构运作。"),
            ("差异政治与正义", "正义不应追求抹平差异的普适原则，而应承认群体差异，并通过制度安排保障不同群体的参与与发言权。"),
        ],
        "works": [
            "*Throwing Like a Girl and Other Essays in Feminist Philosophy and Social Theory* (1990)",
            "*Justice and the Politics of Difference* (1990)",
            "*Inclusion and Democracy* (2000)",
        ],
        "links": [
            "与 [西蒙娜·德·波伏娃](../存在主义/西蒙娜.md) 共享对女性身体处境的分析。",
            "与 [朱迪斯·巴特勒](../../../社会学/学派/性别研究/butler.md) 共同构成当代女性主义身体理论的重要脉络。",
        ],
        "reading": [
            "Young, I. M. *Justice and the Politics of Difference* (1990)",
            "Young, I. M. *Throwing Like a Girl* (1990)",
        ],
    },
    "gilles-deleuze": {
        "path": "哲学/学派/后结构主义/德勒兹.md",
        "title": "吉尔·德勒兹 · Gilles Deleuze",
        "domain": "哲学",
        "school": "post-structuralism",
        "era": "contemporary",
        "birth": 1925,
        "death": 1995,
        "nationality": "法国",
        "tags": ["post-structuralism", "affect", "difference", "rhizome", "becoming"],
        "aliases": ["德勒兹", "Gilles Deleuze", "吉尔·德勒兹"],
        "intro": "吉尔·德勒兹（Gilles Deleuze，1925–1995）是法国哲学家，后结构主义关键人物。他与加塔利提出“块茎”“生成”“欲望机器”等概念，重新思考差异、情感与权力。",
        "theses": [
            ("差异先于同一", "传统哲学将差异视为同一的附属；德勒兹则认为，存在就是差异的生成，同一性是事后建构。"),
            ("情感作为身体之力", "情动（affect）不是主观的情绪，而是身体在遭遇他者时力量增强或减弱的动态过程，先于被命名的情感。"),
            ("块茎思维", "知识不应被还原为树状的等级起源，而应像块茎一样横向连接、多元生成、无中心。"),
        ],
        "works": [
            "*Difference and Repetition* (1968)",
            "*A Thousand Plateaus* (1980, with Félix Guattari)",
            "*What is Philosophy?* (1991, with Félix Guattari)",
        ],
        "links": [
            "与 [巴鲁赫·斯宾诺莎](../理性论/巴鲁赫.md) 在情动理论上遥相呼应，德勒兹将斯宾诺莎的“情感”发展为后结构主义的“情动”。",
            "与 [雅克·德里雅](雅克.md) 共同属于法国后结构主义潮流，但德勒兹更强调力量、生成与身体。",
        ],
        "reading": [
            "Deleuze, G. & Guattari, F. *A Thousand Plateaus* (1980)",
            "Massumi, B. *Parables for the Virtual: Movement, Affect, Sensation* (2002)",
        ],
    },
    "sara-ahmed": {
        "path": "社会学/学派/性别研究/艾哈迈德.md",
        "title": "萨拉·艾哈迈德 · Sara Ahmed",
        "domain": "社会学",
        "school": "gender-studies",
        "era": "contemporary",
        "birth": 1969,
        "nationality": "英国-澳大利亚",
        "tags": ["feminist-theory", "affect", "queer-theory", "race", "cultural-politics"],
        "aliases": ["艾哈迈德", "Sara Ahmed", "萨拉·艾哈迈德"],
        "intro": "萨拉·艾哈迈德（Sara Ahmed，1969– ）是英国女性主义学者与作家，曾任伦敦大学金匠学院教授。她以“情感的文化政治”研究闻名，分析情感如何在话语与制度中流通并建构“他者”。",
        "theses": [
            ("情感的经济", "情感不是私人内在状态，而是在社会中被生产、流通与归属的“经济物”。恐惧、厌恶、爱可以被引导向特定群体。"),
            ("幸福的霸权", "“幸福”常被用作规范工具：偏离主流规范的人被描绘为不快乐，从而合理化对他们的排斥。"),
            ("批判性女性主义的生存", "提出“ killy joy”概念：女性主义者因拒绝配合压迫性的快乐脚本而被视为扫兴者，但这正是批判工作的必要代价。"),
        ],
        "works": [
            "*The Cultural Politics of Emotion* (2004)",
            "*The Promise of Happiness* (2010)",
            "*Living a Feminist Life* (2017)",
        ],
        "links": [
            "与 [朱迪斯·巴特勒](butler.md) 共享对性别规范与情感的批判。",
            "与 [吉尔·德勒兹](../../../哲学/学派/后结构主义/德勒兹.md) 在情动理论上形成对话，但艾哈迈德强调情感的政治归属。",
        ],
        "reading": [
            "Ahmed, S. *The Cultural Politics of Emotion* (2004)",
            "Ahmed, S. *Living a Feminist Life* (2017)",
        ],
    },
    "susan-sontag": {
        "path": "文学/学派/散文家/桑塔格.md",
        "title": "苏珊·桑塔格 · Susan Sontag",
        "domain": "文学",
        "school": "essayists",
        "era": "contemporary",
        "birth": 1933,
        "death": 2004,
        "nationality": "美国",
        "tags": ["essay", "illness", "photography", "aids", "culture"],
        "aliases": ["桑塔格", "Susan Sontag", "苏珊·桑塔格"],
        "intro": "苏珊·桑塔格（Susan Sontag，1933–2004）是美国作家、评论家与公共知识分子。她以《反对阐释》《疾病的隐喻》《关于他人的痛苦》等作品闻名，横跨文学、摄影、疾病伦理与政治批判。",
        "theses": [
            ("反对阐释", "现代批评倾向于把艺术还原为内容或意义，桑塔格呼吁恢复对形式、感性与本真体验的尊重。"),
            ("疾病的隐喻", "疾病常被赋予道德意义（如癌症=压抑，艾滋病=惩罚），这些隐喻不仅错误，还加重患者的羞耻与孤立。"),
            ("摄影的伦理困境", "摄影既是对现实的记录，也是对现实的消费。观看他人的痛苦可能唤醒良知，也可能使我们麻木。"),
        ],
        "works": [
            "*Against Interpretation* (1966)",
            "*Illness as Metaphor* (1978)",
            "*Regarding the Pain of Others* (2003)",
        ],
        "links": [
            "与 [伊莱恩·斯卡里](../../../哲学/学派/政治哲学/斯卡里.md) 共同追问身体、痛苦与语言的关系。",
            "与 [瓦尔特·本雅明](../../../美学/学派/批判美学/瓦尔特/README.md) 共享对机械复制时代的敏感。",
        ],
        "reading": [
            "Sontag, S. *Illness as Metaphor* (1978)",
            "Sontag, S. *Regarding the Pain of Others* (2003)",
        ],
    },
    "emmanuel-levinas": {
        "path": "哲学/学派/现象学/列维纳斯.md",
        "title": "伊曼努尔·列维纳斯 · Emmanuel Levinas",
        "domain": "哲学",
        "school": "phenomenology",
        "era": "contemporary",
        "birth": 1906,
        "death": 1995,
        "nationality": "立陶宛-法国",
        "tags": ["phenomenology", "ethics", "alterity", "face", "judaism"],
        "aliases": ["列维纳斯", "Emmanuel Levinas", "伊曼努尔·列维纳斯"],
        "intro": "伊曼努尔·列维纳斯（Emmanuel Levinas，1906–1995）是立陶宛裔法国哲学家，现象学与犹太思想传统的重要代表。他将伦理学置于第一哲学，强调“他者之脸”对自我的无限责任。",
        "theses": [
            ("他者之脸", "面对面相遇时，他者的脸既向我呈现脆弱，又发出“不可杀人”的伦理命令。它阻止我将他者还原为同一。"),
            ("伦理学作为第一哲学", "不是存在论或知识论优先，而是我对他者的无限责任优先。主体性首先是一种为他者的主体性。"),
            ("享受与脆弱", "生活首先是享受（enjoyment），但享受的他者性与身体的依赖性也构成脆弱的伦理根源。"),
        ],
        "works": [
            "*Totality and Infinity* (1961)",
            "*Otherwise than Being or Beyond Essence* (1974)",
        ],
        "links": [
            "与 [马丁·海德格尔](../存在主义/海德格尔/README.md) 在现象学传统中关系密切，但列维纳斯批评其存在论忽视伦理优先性。",
            "与 [伊曼努尔·康德](../德国唯心论/康德/README.md) 的道德律令形成对话，但列维纳斯的伦理源于面对面的不对称责任。",
        ],
        "reading": [
            "Levinas, E. *Totality and Infinity* (1961)",
            "Critchley, S. *The Problem with Levinas* (2015)",
        ],
    },
    "rachel-carson": {
        "path": "哲学/学派/环境哲学/卡森.md",
        "title": "蕾切尔·卡森 · Rachel Carson",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "birth": 1907,
        "death": 1964,
        "nationality": "美国",
        "tags": ["environmentalism", "ecology", "silent-spring", "conservation"],
        "aliases": ["卡森", "Rachel Carson", "蕾切尔·卡森"],
        "intro": "蕾切尔·卡森（Rachel Carson，1907–1964）是美国海洋生物学家与科普作家，《寂静的春天》作者。她的工作唤起了现代环境运动，将化学污染、生态系统和公共健康联系在一起。",
        "theses": [
            ("化学农药的生态连锁", "DDT 等杀虫剂不只杀死害虫，也通过食物链毒害鸟类、鱼类与人类。生态是一个相互关联的整体。"),
            ("科学写作的公共伦理", "科学家有责任向公众清晰地传达风险，而不是把知识留给专家或产业。"),
            ("自然内在价值", "自然不只是人类的资源库；生物与生态系统具有不依赖经济效用的内在价值。"),
        ],
        "works": [
            "*The Sea Around Us* (1951)",
            "*Silent Spring* (1962)",
        ],
        "links": [
            "与 [奥尔多·利奥波德](利奥波德.md) 共同奠定现代生态伦理：卡森关注污染，利奥波德关注土地伦理。",
            "与 [唐娜·哈拉维](../../../社会学/学派/性别研究/唐娜.md) 共享对科学技术社会后果的批判。",
        ],
        "reading": [
            "Carson, R. *Silent Spring* (1962)",
            "Lear, L. *Rachel Carson: Witness for Nature* (1997)",
        ],
    },
    "aldo-leopold": {
        "path": "哲学/学派/环境哲学/利奥波德.md",
        "title": "奥尔多·利奥波德 · Aldo Leopold",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "modern",
        "birth": 1887,
        "death": 1948,
        "nationality": "美国",
        "tags": ["environmental-ethics", "land-ethic", "conservation", "ecology"],
        "aliases": ["利奥波德", "Aldo Leopold", "奥尔多·利奥波德"],
        "intro": "奥尔多·利奥波德（Aldo Leopold，1887–1948）是美国生态学家、林务员与作家。他在《沙乡年鉴》中提出“土地伦理”，主张将道德共同体的边界从人类扩展到土壤、水、植物与动物。",
        "theses": [
            ("土地伦理", "伦理演化的历史是共同体边界的不断扩展：从自我到家庭、部落、国家，最终应包括整个生物共同体。"),
            ("生物共同体的整体性", "土地不是仅供开发的资源，而是包括土壤、水、植物与动物的复杂生命系统。健康是土地完整、稳定与美丽的同义词。"),
            ("生态良知", "保护不能仅靠法律与经济激励，更需要一种深植于文化的生态良知，让人类视自己为土地的普通成员与公民。"),
        ],
        "works": [
            "*A Sand County Almanac* (1949)",
        ],
        "links": [
            "与 [蕾切尔·卡森](卡森.md) 共同推动现代环境伦理：利奥波德提供伦理框架，卡森揭示化学威胁。",
            "与 [阿尔多·利奥波德](利奥波德.md) 的土地伦理影响了 [阿恩·内斯](内斯.md) 的深层生态学。",
        ],
        "reading": [
            "Leopold, A. *A Sand County Almanac* (1949)",
            "Callicott, J. B. *In Defense of the Land Ethic* (1989)",
        ],
    },
    "james-lovelock": {
        "path": "哲学/学派/环境哲学/洛夫洛克.md",
        "title": "詹姆斯·洛夫洛克 · James Lovelock",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "birth": 1919,
        "death": 2022,
        "nationality": "英国",
        "tags": ["gaia-hypothesis", "earth-systems", "planetary-science", "climate"],
        "aliases": ["洛夫洛克", "James Lovelock", "詹姆斯·洛夫洛克"],
        "intro": "詹姆斯·洛夫洛克（James Lovelock，1919–2022）是英国独立科学家与发明家，以“盖亚假说”闻名。他认为地球是一个自我调节的生命系统，生物圈、大气、海洋与地质过程相互作用，维持适合生命的环境。",
        "theses": [
            ("盖亚假说", "地球可被视为一个自我调节的复杂系统：生物体与无机环境共同演化，维持大气成分、温度与化学状态的相对稳定。"),
            ("行星层面的整体观", "生命不能仅从局部有机体理解，而应看作行星尺度的过程。地球本身展现出类似生命的特征。"),
            ("气候危机的反馈", "人类活动打破盖亚系统的自我调节，可能触发不可逆的临界点。洛夫洛克晚年对气候未来持悲观但行动主义的立场。"),
        ],
        "works": [
            "*Gaia: A New Look at Life on Earth* (1979)",
            "*The Revenge of Gaia* (2006)",
        ],
        "links": [
            "与 [布鲁诺·拉图尔](../../../社会学/学派/行动者网络/拉图尔.md) 共享对自然/社会二元的挑战，但拉图尔更强调行动者网络的多元异质性。",
            "与 [蒂莫西·莫顿](莫顿.md) 的超对象概念共同构成当代行星思维的重要资源。",
        ],
        "reading": [
            "Lovelock, J. *Gaia: A New Look at Life on Earth* (1979)",
            "Lovelock, J. *The Revenge of Gaia* (2006)",
        ],
    },
    "arne-naess": {
        "path": "哲学/学派/环境哲学/内斯.md",
        "title": "阿恩·内斯 · Arne Næss",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "birth": 1912,
        "death": 2009,
        "nationality": "挪威",
        "tags": ["deep-ecology", "ecosophy", "self-realization", "environmental-philosophy"],
        "aliases": ["内斯", "Arne Næss", "阿恩·内斯"],
        "intro": "阿恩·内斯（Arne Næss，1912–2009）是挪威哲学家，深层生态学（deep ecology）的创始人。他区分“浅层生态学”（资源管理）与“深层生态学”（生态中心主义与自我实现）。",
        "theses": [
            ("深层与浅层生态学", "浅层生态学只关心污染与资源对人类的影响；深层生态学追问人类中心主义本身，主张生态系统的内在价值。"),
            ("生态自我", "真正的自我实现不是个人成功，而是“大我”的扩展：将自我认同从个体扩展到社区、物种与生态系统。"),
            ("多样性与共生", "自然的丰富性与复杂性本身具有价值。人类应减少人口与消费，给其他生命留下空间。"),
        ],
        "works": [
            "*Ecology, Community and Lifestyle* (1989)",
        ],
        "links": [
            "与 [奥尔多·利奥波德](利奥波德.md) 的土地伦理一脉相承，但内斯将共同体边界扩展到整个生态系统。",
            "与 [默里·布克钦](布克钦.md) 的社会生态学存在论争：内斯强调个体意识转变，布克钦强调社会结构变革。",
        ],
        "reading": [
            "Næss, A. *Ecology, Community and Lifestyle* (1989)",
            "Sessions, G. (ed.) *Deep Ecology for the Twenty-First Century* (1995)",
        ],
    },
    "murray-bookchin": {
        "path": "哲学/学派/环境哲学/布克钦.md",
        "title": "默里·布克钦 · Murray Bookchin",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "birth": 1921,
        "death": 2006,
        "nationality": "美国",
        "tags": ["social-ecology", "libertarian-municipalism", "anarchism", "environment"],
        "aliases": ["布克钦", "Murray Bookchin", "默里·布克钦"],
        "intro": "默里·布克钦（Murray Bookchin，1921–2006）是美国社会理论家与无政府主义者，社会生态学的创始人。他认为生态危机根源于社会等级制与统治关系，解决生态问题必须同时改造社会结构。",
        "theses": [
            ("社会生态学", "生态问题不是抽象的人口或技术问题，而是社会等级制、阶级统治与商品化的结果。人类对自然的支配复制了人对人的支配。"),
            ("自由市镇主义", "直接民主的地方自治共同体是替代国家与资本主义的政治形式，也是生态社会的制度基础。"),
            ("差异中的统一", "自然不是铁板一块的“整体”，而是差异与自发性的辩证统一。生态思维应反对把自然浪漫化或神秘化。"),
        ],
        "works": [
            "*Post-Scarcity Anarchism* (1971)",
            "*The Ecology of Freedom* (1982)",
        ],
        "links": [
            "与 [卡尔·马克思](../../../社会学/学派/古典社会学/马克思/README.md) 共享对社会结构变革的关注，但布克钦更强调去中心化的直接民主。",
            "与 [阿恩·内斯](内斯.md) 的深层生态学形成著名论争：布克钦批评其神秘主义倾向。",
        ],
        "reading": [
            "Bookchin, M. *The Ecology of Freedom* (1982)",
            "Bookchin, M. *Post-Scarcity Anarchism* (1971)",
        ],
    },
    "val-plumwood": {
        "path": "哲学/学派/环境哲学/普拉姆伍德.md",
        "title": "瓦尔·普拉姆伍德 · Val Plumwood",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "birth": 1939,
        "death": 2008,
        "nationality": "澳大利亚",
        "tags": ["ecofeminism", "environmental-philosophy", "colonialism", "reason"],
        "aliases": ["普拉姆伍德", "Val Plumwood"],
        "intro": "瓦尔·普拉姆伍德（Val Plumwood，1939–2008）是澳大利亚生态女性主义哲学家。她在《女性主义与对自然的主宰》中批判西方理性传统中的二元论——理性/自然、男性/女性、文明/野蛮——如何共同为生态破坏与压迫辩护。",
        "theses": [
            ("理性主义与自然的他者化", "西方理性传统将“理性”等同于人类（尤其是白人男性），把自然、女性与有色人种贬为低等的“他者”，从而合法化统治。"),
            ("生态女性主义的批判", "对自然的支配与对女性的支配共享同一套逻辑：将对象视为可被占有、利用与控制的资源。"),
            ("关系性自我", "反对原子化、自主的理性自我，主张人是嵌入自然与社会关系网络中的存在；生态伦理应基于相互依存而非支配。"),
        ],
        "works": [
            "*Feminism and the Mastery of Nature* (1993)",
            "*Environmental Culture: The Ecological Crisis of Reason* (2002)",
        ],
        "links": [
            "与 [朱迪斯·巴特勒](../../../社会学/学派/性别研究/butler.md) 共享对身份与规范的批判，但普拉姆伍德将批判延伸至自然与理性传统。",
            "与 [默里·布克钦](布克钦.md) 都关注统治结构，但普拉姆伍德强调性别、种族与殖民维度。",
        ],
        "reading": [
            "Plumwood, V. *Feminism and the Mastery of Nature* (1993)",
            "Plumwood, V. *Environmental Culture* (2002)",
        ],
    },
    "timothy-morton": {
        "path": "哲学/学派/环境哲学/莫顿.md",
        "title": "蒂莫西·莫顿 · Timothy Morton",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "birth": 1968,
        "nationality": "英国-美国",
        "tags": ["hyperobjects", "ecology", "object-oriented-ontology", "anthropocene"],
        "aliases": ["莫顿", "Timothy Morton", "蒂莫西·莫顿"],
        "intro": "蒂莫西·莫顿（Timothy Morton，1968– ）是英国哲学家与生态理论家，提出“超对象”（hyperobjects）概念，用以描述气候变化、塑料、核辐射等巨大、分散、跨时空存在物，深刻影响了人类世思想。",
        "theses": [
            ("超对象", "超对象巨大而分散，无法被直接把握，却渗透在日常生活中。它们挑战了传统的主体-客体、自然-文化二分。"),
            ("人类世的生态思维", "人类世意味着自然已不存在：没有任何“自然”区域不受人类影响。生态学必须放弃对纯真自然的怀旧。"),
            ("怪诞生态学", "生态关系是亲密而怪诞的：我们与数百万种生命、化学物质和技术产品纠缠在一起，无法保持审美距离。"),
        ],
        "works": [
            "*The Ecological Thought* (2010)",
            "*Hyperobjects: Philosophy and Ecology after the End of the World* (2013)",
            "*Dark Ecology: For a Logic of Future Coexistence* (2016)",
        ],
        "links": [
            "与 [布鲁诺·拉图尔](../../../社会学/学派/行动者网络/拉图尔.md) 共享对自然/社会二元与行动者网络的关注。",
            "与 [詹姆斯·洛夫洛克](洛夫洛克.md) 的盖亚假说共同构成行星尺度的生态想象。",
        ],
        "reading": [
            "Morton, T. *Hyperobjects* (2013)",
            "Morton, T. *Dark Ecology* (2016)",
        ],
    },
}

# -----------------------------------------------------------------------------
# Quote entries (36 = 12 themes × 3 quotes)
# -----------------------------------------------------------------------------
QUOTES = [
    # -------------------------------------------------------------------------
    # Group 1
    # -------------------------------------------------------------------------
    {
        "theme": "科学理性",
        "filename": "波普尔-黑天鹅与证伪.md",
        "id": "quote-popper-black-swan",
        "title": "黑天鹅与证伪",
        "author": "卡尔·波普尔 (Karl Popper)",
        "author_era": "1902–1994",
        "author_nationality": "奥地利-英国",
        "domain": "哲学",
        "school": "philosophy-of-science",
        "era": "contemporary",
        "year": 1959,
        "original_language": "en",
        "tags": ["falsificationism", "scientific-method", "black-swan", "科学理性"],
        "mood": "冷峻",
        "cross_ref_id": "popper",
        "original": "No number of sightings of white swans can prove the theory that all swans are white; the sighting of one black swan can disprove it.",
        "translation": "无论看到多少只白天鹅，都无法证明“所有天鹅都是白的”这一理论；而一只黑天鹅就足以推翻它。",
        "source": "Popper, *The Logic of Scientific Discovery* (1959)",
        "context": "卡尔·波普尔在《科学发现的逻辑》中提出，科学理论的本质特征不是可证实，而是可证伪。科学家应主动寻找能够推翻自己理论的证据，而非只收集确证案例。",
        "interpretation": [
            ("从归纳到证伪", "传统经验主义相信科学来自归纳：观察足够多白天鹅就能得出普遍结论。波普尔指出归纳在逻辑上无法保证普遍真理。"),
            ("科学进步的动力", "科学通过“猜想与反驳”前进：提出大胆假说，再竭尽全力证伪它。 survived 的暂时不是真理，而是尚未被推翻的最佳假说。"),
            ("对确定性的放弃", "证伪主义意味着科学永远带有临时性。它不追求绝对真理，而是追求越来越好的近似与越来越强的可检验性。"),
        ],
        "genealogy": [
            ("休谟", "归纳问题", "普遍结论无法从有限观察逻辑推出"),
            ("波普尔", "证伪主义", "可证伪性是科学与非科学的分界"),
            ("库恩", "范式革命", "证伪不足以解释科学变革，社会因素同样重要"),
        ],
        "hooks": {
            "cover": "一只黑天鹅，如何推翻千万只白天鹅建立的“真理”？",
            "video": "1959 年，波普尔用一只黑天鹅告诉世界：科学不是证明，而是不断尝试被推翻。",
            "social": "你收集再多的“成功证据”，也抵不过一次致命的反例。真正的理性，是主动寻找能推翻自己的黑天鹅。",
        },
        "visual": "一只黑天鹅掠过平静的湖面，倒影中无数白天鹅的剪影碎裂；配色黑白对比，冷峻而锐利。",
        "further": [
            "Popper, K. *The Logic of Scientific Discovery* (1959)",
            "Popper, K. *Conjectures and Refutations* (1963)",
        ],
    },
    {
        "theme": "科学理性",
        "filename": "库恩-范式革命.md",
        "id": "quote-kuhn-paradigm-shift",
        "title": "范式革命",
        "author": "托马斯·库恩 (Thomas Kuhn)",
        "author_era": "1922–1996",
        "author_nationality": "美国",
        "domain": "哲学",
        "school": "philosophy-of-science",
        "era": "contemporary",
        "year": 1962,
        "original_language": "en",
        "tags": ["paradigm", "scientific-revolution", "incommensurability", "科学理性"],
        "mood": "激越",
        "cross_ref_id": "kuhn",
        "original": "The transition from a paradigm in crisis to a new one from which still newer tradition of normal science can emerge is far from a cumulative process, achieved by an articulation or extension of the old paradigm. It is a reconstruction of the field from new fundamentals.",
        "translation": "从危机中的范式过渡到能够产生新的常规科学传统的新范式，绝非一个累积过程，也不是通过对旧范式的阐发或扩展就能完成。它是对整个领域从新的基础出发的重构。",
        "source": "Kuhn, *The Structure of Scientific Revolutions* (1962)",
        "context": "托马斯·库恩在《科学革命的结构》中挑战科学进步的线性图景。他认为科学发展是“常规科学—危机—革命—新常规科学”的循环，范式转换不仅是理论更替，更是看世界方式的转换。",
        "interpretation": [
            ("范式作为整体世界观", "范式不仅是具体理论，还包含方法、价值与形而上学承诺。不同范式的科学家可能用相同的术语谈论不同的世界。"),
            ("不可通约性", "新旧范式之间往往缺乏中立的评判标准。这并不意味着科学是任意的，而是说明科学选择受历史、美学与社群实践的影响。"),
            ("革命而非累积", "科学革命不是旧知识的简单相加，而是概念框架的根本重组。牛顿力学与相对论之间不是简单的“扩展”关系。"),
        ],
        "genealogy": [
            ("康德", "认识框架", "经验由范畴结构塑造"),
            ("波普尔", "证伪主义", "通过反驳推动理论更替"),
            ("库恩", "范式理论", "社会与历史维度进入科学哲学"),
        ],
        "hooks": {
            "cover": "科学革命不是知识累积，而是世界观的重构。",
            "video": "1962 年，库恩说：科学进步不是爬楼梯，而是一场场世界观的革命。",
            "social": "当旧框架无法解释越来越多的异常，真正的进步不是修补，而是敢于换一种方式看世界。",
        },
        "visual": "一座旧建筑的地基被整体替换，新的结构从废墟中升起；配色从沉稳的灰蓝过渡到炽烈的橙红。",
        "further": [
            "Kuhn, T. *The Structure of Scientific Revolutions* (1962)",
            "Lakatos, I. & Musgrave, A. (eds.) *Criticism and the Growth of Knowledge* (1970)",
        ],
    },
    {
        "theme": "科学理性",
        "filename": "费耶阿本德-怎么都行.md",
        "id": "quote-feyerabend-anything-goes",
        "title": "怎么都行",
        "author": "保罗·费耶阿本德 (Paul Feyerabend)",
        "author_era": "1924–1994",
        "author_nationality": "奥地利-美国",
        "domain": "哲学",
        "school": "philosophy-of-science",
        "era": "contemporary",
        "year": 1975,
        "original_language": "en",
        "tags": ["epistemological-anarchism", "scientific-pluralism", "method", "科学理性"],
        "mood": "叛逆",
        "cross_ref_id": "paul-feyerabend",
        "original": "The only principle that does not inhibit progress is: anything goes.",
        "translation": "唯一不妨碍进步的原则是：怎么都行。",
        "source": "Feyerabend, *Against Method* (1975)",
        "context": "费耶阿本德在《反对方法》中以历史案例说明，科学史中的重大进步往往违反当时公认的方法论。伽利略的胜利不仅依赖观察，更依赖修辞、宣传与新柏拉图主义信念。",
        "interpretation": [
            ("方法论的神话", "不存在普遍有效的科学方法。任何方法论规则在历史中都能找到反例，把方法绝对化反而会扼杀创新。"),
            ("科学多元主义", "神话、巫术、占星术与现代科学并非理性等级的不同阶段，而是多元传统。科学的霸权地位是社会政治结果，而非认识论必然。"),
            ("“怎么都行”不是虚无主义", "费耶阿本德并非主张随便怎么做都好，而是反对以单一方法扼杀尝试。进步需要宽容与冒险。"),
        ],
        "genealogy": [
            ("波普尔", "证伪主义", "强调方法规则"),
            ("库恩", "范式理论", "强调历史与不可通约性"),
            ("费耶阿本德", "认识论无政府主义", "彻底反对方法一元论"),
        ],
        "hooks": {
            "cover": "科学的进步，始于敢于打破规则。",
            "video": "他说“怎么都行”：科学史上最叛逆的哲学家，为什么反对所有方法论？",
            "social": "当你被告知“必须按规矩来”，也许该问：这条规矩保护的是进步，还是既得利益？",
        },
        "visual": "打破量杯与公式符号的拼贴，背景是星空与炼金术图案；配色叛逆，紫红与电蓝交织。",
        "further": [
            "Feyerabend, P. *Against Method* (1975)",
            "Feyerabend, P. *Science in a Free Society* (1978)",
        ],
    },
    {
        "theme": "怀疑方法",
        "filename": "笛卡尔-我思故我在.md",
        "id": "quote-descartes-cogito",
        "title": "我思故我在",
        "author": "勒内·笛卡尔 (René Descartes)",
        "author_era": "1596–1650",
        "author_nationality": "法国",
        "domain": "哲学",
        "school": "rationalism",
        "era": "early-modern",
        "year": 1637,
        "original_language": "la",
        "tags": ["doubt", "cogito", "rationalism", "怀疑方法"],
        "mood": "孤寂",
        "cross_ref_id": "descartes",
        "original": "Cogito, ergo sum.",
        "translation": "我思，故我在。",
        "source": "Descartes, *Discours de la méthode* (1637); *Principia philosophiae* (1644)",
        "context": "笛卡尔在《谈谈方法》中提出普遍怀疑：凡能稍加怀疑者，皆不可作为确定基础。然而，怀疑本身无法怀疑正在怀疑的“我”，故“我思”成为第一确定性。",
        "interpretation": [
            ("怀疑作为方法", "笛卡尔不否定知识，而是要用最彻底的怀疑为知识奠基。错误接受不如暂时悬置判断。"),
            ("主体性的发现", "“我思故我在”将“我”确立为思维实体。近代哲学的“主体”由此诞生，开启了认识论转向。"),
            ("理性的根基", "即使感官与世界皆可能欺骗，理性仍在运作。数学式的清晰明白成为真理标准。"),
        ],
        "genealogy": [
            ("苏格拉底", "诘问法", "通过追问揭示无知"),
            ("笛卡尔", "普遍怀疑", "以怀疑为方法确立确定性"),
            ("休谟", "怀疑主义", "怀疑理性因果推论的必然性"),
        ],
        "hooks": {
            "cover": "怀疑一切之后，还有什么能确定？",
            "video": "笛卡尔把世界全部怀疑掉，只留下一句话：我思，故我在。",
            "social": "在信息爆炸的时代，最该怀疑的不是世界，而是你以为已经确信的结论。",
        },
        "visual": "一个人影坐在昏暗的书房，烛光中只有眼睛与思考的线条清晰；配色深褐与金，孤独而坚定。",
        "further": [
            "Descartes, R. *Discourse on the Method* (1637)",
            "Descartes, R. *Meditations on First Philosophy* (1641)",
        ],
    },
    {
        "theme": "怀疑方法",
        "filename": "休谟-习惯是人生的伟大指南.md",
        "id": "quote-hume-custom",
        "title": "习惯是人生的伟大指南",
        "author": "大卫·休谟 (David Hume)",
        "author_era": "1711–1776",
        "author_nationality": "苏格兰",
        "domain": "哲学",
        "school": "empiricism",
        "era": "early-modern",
        "year": 1748,
        "original_language": "en",
        "tags": ["custom", "habit", "causality", "empiricism", "怀疑方法"],
        "mood": "温厚",
        "cross_ref_id": "hume",
        "original": "Custom, then, is the great guide of human life.",
        "translation": "因此，习惯是人生的伟大指南。",
        "source": "Hume, *An Enquiry Concerning Human Understanding* (1748)",
        "context": "休谟在《人类理解研究》中质疑因果关系的理性基础：我们从未直接观察到“必然联系”，只是 repeatedly 看到事件相继发生，由此形成习惯预期。理性无法证明太阳明天会升起，是习惯让我们如此相信。",
        "interpretation": [
            ("因果关系的习惯来源", "因果不是理性洞见，而是心理习惯。当我们反复经验到 B 紧随 A，心灵便产生从 A 想到 B 的倾向。"),
            ("怀疑的限度", "休谟的怀疑不是为否定世界，而是为揭示人类知识的真正基础：经验、习惯与想象。"),
            ("对独断理性的温和", "与其追求无法达到的确定性，不如接受习惯与或然性作为行动指南。怀疑之后，生活照常。"),
        ],
        "genealogy": [
            ("笛卡尔", "理性怀疑", "通过理性寻找确定性"),
            ("洛克", "经验主义", "知识源于观念与经验"),
            ("休谟", "习惯心理学", "因果是心理习惯而非理性证明"),
        ],
        "hooks": {
            "cover": "你相信的因果，可能只是习惯。",
            "video": "休谟说：习惯才是人生的伟大指南。我们以为的理性，其实多是惯性。",
            "social": "别急着把“一直如此”当成“理应如此”。习惯是路标，不是判决书。",
        },
        "visual": "一条被千万次脚步踏出的小径，晨雾中延伸；配色柔和的灰绿与暖黄，暗示习惯的温柔力量。",
        "further": [
            "Hume, D. *An Enquiry Concerning Human Understanding* (1748)",
            "Hume, D. *A Treatise of Human Nature* (1739–40)",
        ],
    },
    {
        "theme": "怀疑方法",
        "filename": "皮尔士-怀疑的固定.md",
        "id": "quote-peirce-fixation-of-belief",
        "title": "怀疑的固定",
        "author": "查尔斯·桑德斯·皮尔士 (Charles Sanders Peirce)",
        "author_era": "1839–1914",
        "author_nationality": "美国",
        "domain": "哲学",
        "school": "pragmatism",
        "era": "modern",
        "year": 1877,
        "original_language": "en",
        "tags": ["doubt", "belief", "pragmatism", "inquiry", "怀疑方法"],
        "mood": "清明",
        "cross_ref_id": "哲学.pragmatism.peirce",
        "original": "Doubt is an uneasy and dissatisfied state from which we struggle to free ourselves and pass into the state of belief; while the latter is a calm and satisfactory state which we do not wish to avoid, or to change to a belief in anything else.",
        "translation": "怀疑是一种不安与不满的状态，我们努力从中解脱，进入信念的状态；信念则是一种平静而满意的状态，我们不愿回避它，也不愿改信别的东西。",
        "source": "Peirce, *The Fixation of Belief* (1877)",
        "context": "皮尔士在《信念的固定》中提出，探究的起点不是笛卡尔式的普遍怀疑，而是真实存在的“不安的怀疑”。探究的目的就是通过科学方法固定信念，使人摆脱怀疑的扰动。",
        "interpretation": [
            ("怀疑不是游戏", "真正的怀疑伴随着不安与行动冲动，而非哲学课上为怀疑而怀疑。怀疑驱动我们去探究。"),
            ("固定信念的四种方法", "皮尔士梳理了固执、权威、先验与科学四种固定信念的方法，认为唯有科学方法能让信念接受经验的持续检验。"),
            ("实用主义的起点", "信念的意义在于它如何引导行动与习惯。探究不是找到永恒的真理，而是找到能稳定指导实践的信念。"),
        ],
        "genealogy": [
            ("笛卡尔", "普遍怀疑", "以怀疑为方法工具"),
            ("休谟", "习惯心理学", "信念源于习惯"),
            ("皮尔士", "实用主义探究", "怀疑驱动探究，科学固定信念"),
        ],
        "hooks": {
            "cover": "怀疑让你不安，而信念让你平静——这就是探究的引擎。",
            "video": "1877 年，皮尔士重新定义怀疑：真正让人行动的怀疑，不是哲学游戏，而是不安。",
            "social": "别害怕怀疑带来的不适感，那正是你真正开始思考的信号。",
        },
        "visual": "一条小船从迷雾（怀疑）驶向平静的港湾（信念），海面由湍急渐变开阔；配色从灰蓝过渡到暖金。",
        "further": [
            "Peirce, C. S. *The Fixation of Belief* (1877)",
            "Peirce, C. S. *How to Make Our Ideas Clear* (1878)",
        ],
    },
    {
        "theme": "语言游戏",
        "filename": "维特根斯坦-语言游戏.md",
        "id": "quote-wittgenstein-language-game",
        "title": "语言游戏",
        "author": "路德维希·维特根斯坦 (Ludwig Wittgenstein)",
        "author_era": "1889–1951",
        "author_nationality": "奥地利-英国",
        "domain": "哲学",
        "school": "analytic-philosophy",
        "era": "contemporary",
        "year": 1953,
        "original_language": "de",
        "tags": ["language-game", "meaning-as-use", "forms-of-life", "语言游戏"],
        "mood": "明净",
        "cross_ref_id": "wittgenstein",
        "original": "Die Bedeutung eines Wortes ist sein Gebrauch in der Sprache.",
        "translation": "一个词的意义就是它在语言中的使用。",
        "source": "Wittgenstein, *Philosophische Untersuchungen* (1953), §43",
        "context": "维特根斯坦在《哲学研究》中放弃早期《逻辑哲学论》对语言图像论的追寻，提出“语言游戏”概念。语言的意义不在所指对象，而在具体生活形式中的使用规则。",
        "interpretation": [
            ("意义即使用", "问“一个词的意思是什么”，不如问“这个词如何使用”。脱离具体语言游戏，追问本质意义往往导致哲学迷雾。"),
            ("生活形式", "语言游戏嵌于特定的生活形式中。命令、祈祷、玩笑、描述各有规则，无法被还原为单一的“语言本质”。"),
            ("治疗性哲学", "哲学的任务不是建立理论，而是澄清语言误用，把思想从语言的蛊惑中解放出来。"),
        ],
        "genealogy": [
            ("奥古斯丁", "语言图画", "词对应物"),
            ("维特根斯坦前期", "图像论", "语言逻辑地描绘世界"),
            ("维特根斯坦后期", "语言游戏", "意义在于使用与生活形式"),
        ],
        "hooks": {
            "cover": "别问“这是什么意思”，问“它是怎么用的”。",
            "video": "维特根斯坦：一个词的意义，不是它指什么，而是你怎么用它。",
            "social": "很多争论不是观点不同，而是我们把同一个词玩成了不同的语言游戏。",
        },
        "visual": "多扇窗户映射不同的生活场景：命令、祈祷、玩笑、计数；每扇窗的词语发光方式不同；配色明亮而秩序感强。",
        "further": [
            "Wittgenstein, L. *Philosophical Investigations* (1953)",
            "Wittgenstein, L. *The Blue and Brown Books* (1958)",
        ],
    },
    {
        "theme": "语言游戏",
        "filename": "奥斯汀-说话即做事.md",
        "id": "quote-austin-do-things-with-words",
        "title": "说话即做事",
        "author": "约翰·奥斯汀 (J. L. Austin)",
        "author_era": "1911–1960",
        "author_nationality": "英国",
        "domain": "哲学",
        "school": "analytic-philosophy",
        "era": "contemporary",
        "year": 1955,
        "original_language": "en",
        "tags": ["speech-acts", "performative", "ordinary-language", "语言游戏"],
        "mood": "机敏",
        "cross_ref_id": "john-austin",
        "original": "To say something is to do something.",
        "translation": "说出某事就是在做某事。",
        "source": "Austin, *How to Do Things with Words* (1962, based on 1955 William James Lectures)",
        "context": "奥斯汀在1955年哈佛威廉·詹姆斯讲座中提出“言语行为理论”。他区分记述式（描述真假）与施行式（完成行为），后来发展为言内、言外、言后三层行为分析。",
        "interpretation": [
            ("施行话语", "“我道歉”“我承诺”“我命名”这些话不是在描述世界，而是在改变社会事实。它们的恰当性取决于语境与规则。"),
            ("言语的社会性", "说话不仅是表达思想，更是参与社会制度。言说者、听者、场合、身份共同决定话语能否成功“做某事”。"),
            ("对语言哲学的扩展", "奥斯汀把语言哲学从意义与真理，扩展到行动、权力与规范，影响了法学、文学与社会理论。"),
        ],
        "genealogy": [
            ("维特根斯坦", "语言游戏", "语言作为活动"),
            ("奥斯汀", "言语行为", "说话即做事"),
            ("塞尔", "言语行为系统化", "意向性与制度事实"),
        ],
        "hooks": {
            "cover": "一句“我承诺”，不只是声音，而是一份债务。",
            "video": "奥斯汀：说话时，你不仅在描述世界，还在改变它。",
            "social": "语言不是镜子，而是工具。每一次表达，都可能是在建立、伤害或改变世界。",
        },
        "visual": "一张嘴说出的话化作契约、印章与握手；背景是法庭与婚礼场景；配色庄重而温暖。",
        "further": [
            "Austin, J. L. *How to Do Things with Words* (1962)",
            "Searle, J. *Speech Acts* (1969)",
        ],
    },
    {
        "theme": "语言游戏",
        "filename": "索绪尔-符号的任意性.md",
        "id": "quote-saussure-arbitrariness",
        "title": "符号的任意性",
        "author": "费尔迪南·德·索绪尔 (Ferdinand de Saussure)",
        "author_era": "1857–1913",
        "author_nationality": "瑞士",
        "domain": "美学",
        "school": "literary-theory",
        "era": "modern",
        "year": 1916,
        "original_language": "fr",
        "tags": ["semiology", "arbitrariness", "signifier", "语言游戏"],
        "mood": "冷峻",
        "cross_ref_id": "saussure",
        "original": "Le signe linguistique est arbitraire.",
        "translation": "语言符号是任意的。",
        "source": "Saussure, *Cours de linguistique générale* (1916)",
        "context": "索绪尔在《普通语言学教程》中提出，语言符号的能指（声音形象）与所指（概念）之间的联系没有自然必然性。“树”为什么叫 shù 或 tree，是社会约定而非自然模仿。",
        "interpretation": [
            ("任意性不是个人随意", "任意性指能指与所指之间无内在联系，但符号一旦被社会约定，对个体具有强制性。你不能凭个人意志改变“水”的读音。"),
            ("差异构成意义", "语言中每个词的价值不在于其自身，而在于它与其他词的差异。意义是系统内关系的结果。"),
            ("语言作为系统", "语言（langue）是社会共有的符号系统，言语（parole）是个体对系统的具体使用。结构主义由此兴起。"),
        ],
        "genealogy": [
            ("柏拉图", "克拉底鲁篇", "名称是否天然正确"),
            ("索绪尔", "结构语言学", "符号任意性与差异系统"),
            ("维特根斯坦", "语言游戏", "意义在于使用规则"),
        ],
        "hooks": {
            "cover": "“树”为什么叫树？答案不在树里，而在约定里。",
            "video": "索绪尔：语言符号是任意的。同一个世界，不同语言切出了不同的意义。",
            "social": "你以为的“天然”称呼，其实是社会约定的冰山。换个语言，世界就换个形状。",
        },
        "visual": "同一个物体被不同语言的标签环绕：tree、arbre、木、дерево；标签颜色各异，物体本身静默；配色冷灰与霓虹对比。",
        "further": [
            "Saussure, F. de. *Course in General Linguistics* (1916)",
            "Culler, J. *Saussure* (1976)",
        ],
    },
    # -------------------------------------------------------------------------
    # Group 2
    # -------------------------------------------------------------------------
    {
        "theme": "技术异化",
        "filename": "海德格尔-技术的本质.md",
        "id": "quote-heidegger-essence-of-technology",
        "title": "技术的本质",
        "author": "马丁·海德格尔 (Martin Heidegger)",
        "author_era": "1889–1976",
        "author_nationality": "德国",
        "domain": "哲学",
        "school": "existentialism",
        "era": "contemporary",
        "year": 1953,
        "original_language": "de",
        "tags": ["technology", "enframing", "gestell", "技术异化"],
        "mood": "沉郁",
        "cross_ref_id": "heidegger",
        "original": "Die Technik ist nicht gleich Technisches.",
        "translation": "技术并不等同于技术性的东西。",
        "source": "Heidegger, *Die Frage nach der Technik* (1953)",
        "context": "海德格尔在《技术的追问》中区分技术的本质与具体技术物。现代技术的本质是一种“座架”（Ge-stell），它将自然与人类都还原为可被计算、储存与支配的“持存物”。",
        "interpretation": [
            ("座架作为揭示方式", "技术不只是工具，而是一种理解世界的方式。在座架中，河流不再被视为河流，而是水力资源；森林是木材储备。"),
            ("危险与拯救", "座架是最极端的危险，因为它可能使人类也把自己看作可优化的资源。但危险深处也藏着转向：只有追问技术的本质，才能开启另一种关系。"),
            ("反对工具论与目的论", "把技术只看做达成目的的手段，遮蔽了其更根本的存在论影响。技术改变了我们与世界相遇的方式。"),
        ],
        "genealogy": [
            ("亚里士多德", "四因说", "技艺作为因果揭示"),
            ("马克思", "异化劳动", "技术作为资本控制劳动的中介"),
            ("海德格尔", "座架", "技术作为存在论框架"),
        ],
        "hooks": {
            "cover": "技术不只是工具，它是一种看世界的方式。",
            "video": "海德格尔警告：当一切都变成资源，人也会把自己变成资源。",
            "social": "别让“效率”成为你理解世界唯一的滤镜。技术越强大，越要追问它的本质。",
        },
        "visual": "一条河流被水坝、电网与数据流包围，逐渐失去“河流”的面容；色调冷灰与工业蓝，压抑而庄严。",
        "further": [
            "Heidegger, M. *The Question Concerning Technology* (1953)",
            "Heidegger, M. *Building Dwelling Thinking* (1951)",
        ],
    },
    {
        "theme": "技术异化",
        "filename": "马尔库塞-单向度的人.md",
        "id": "quote-marcuse-one-dimensional-man",
        "title": "单向度的人",
        "author": "赫伯特·马尔库塞 (Herbert Marcuse)",
        "author_era": "1898–1979",
        "author_nationality": "德国-美国",
        "domain": "伦理政治",
        "school": "critical-theory",
        "era": "contemporary",
        "year": 1964,
        "original_language": "en",
        "tags": ["one-dimensional", "technological-rationality", "critical-theory", "技术异化"],
        "mood": "冷峻",
        "cross_ref_id": "marcuse",
        "original": "A comfortable, smooth, reasonable, democratic unfreedom prevails in advanced industrial civilization.",
        "translation": "在发达的工业文明中，一种舒适、顺滑、合理、民主的不自由盛行着。",
        "source": "Marcuse, *One-Dimensional Man* (1964)",
        "context": "马尔库塞在《单向度的人》中批判发达工业社会：技术进步与消费主义共同生产出一种“舒适的奴役”。人们满足于虚假需求，批判性思维的否定维度被收编。",
        "interpretation": [
            ("虚假需求与真实需求", "广告与消费文化制造出“你需要更多”的幻象。真实需求关乎自由与解放，却被系统化的欲望取代。"),
            ("技术理性作为意识形态", "技术理性原本追求效率与控制自然，如今也成为控制人的意识形态。它使压迫看起来自然且合理。"),
            ("单向度社会的危险", "当批判话语被同化为管理话语，社会失去了说“不”的能力。自由只剩下选择商品款式的自由。"),
        ],
        "genealogy": [
            ("马克思", "商品拜物教", "人的关系被物的关系掩盖"),
            ("韦伯", "理性化铁笼", "工具理性膨胀"),
            ("马尔库塞", "单向度", "技术理性消解批判意识"),
        ],
        "hooks": {
            "cover": "最牢固的牢笼，是你根本不想出去。",
            "video": "马尔库塞：发达工业社会让你自由选择，却从不问你需不需要这些选择。",
            "social": "当你的不满只剩下“选 A 还是选 B”，也许该问：是谁决定了只有 A 和 B？",
        },
        "visual": "一个人坐在贴满广告与选项的房间里，四周墙壁由屏幕组成，门被隐藏在选项之后；配色高饱和却窒息。",
        "further": [
            "Marcuse, H. *One-Dimensional Man* (1964)",
            "Marcuse, H. *Eros and Civilization* (1955)",
        ],
    },
    {
        "theme": "技术异化",
        "filename": "艾吕尔-技术自主性.md",
        "id": "quote-ellul-autonomous-technique",
        "title": "技术自主性",
        "author": "雅克·艾吕尔 (Jacques Ellul)",
        "author_era": "1912–1994",
        "author_nationality": "法国",
        "domain": "哲学",
        "school": "philosophy-of-technology",
        "era": "contemporary",
        "year": 1954,
        "original_language": "fr",
        "tags": ["technique", "autonomy", "efficiency", "技术异化"],
        "mood": "警醒",
        "cross_ref_id": "jacques-ellul",
        "original": "Technique has become autonomous; it has fashioned an omnivorous world which obeys its own laws and which has renounced all tradition.",
        "translation": "技术已经变得自主；它塑造了一个服从自身法则、抛弃一切传统的贪得无厌的世界。",
        "source": "Ellul, *La Technique ou l'Enjeu du siècle* (1954)",
        "context": "艾吕尔在《技术社会》中指出，技术（technique）已从人类工具演变为自主系统。效率、计算与标准化成为不可阻挡的内在法则，政治、伦理与宗教传统被迫让位。",
        "interpretation": [
            ("技术不是工具的集合", "艾吕尔所说的“技术”不是机器，而是一种以效率为最高准则的行事方式。它渗透到教育、法律、艺术与宗教。"),
            ("自主性的含义", "技术系统自我增长、自我修正，人类选择看似自由，实则被效率逻辑预先结构化。"),
            ("传统的失效", "道德与宗教传统无法有效约束技术，因为它们本身也被技术化：宗教使用数据营销，伦理被成本收益分析接管。"),
        ],
        "genealogy": [
            ("马克思", "机器与异化", "技术作为资本权力"),
            ("海德格尔", "座架", "技术作为存在论揭示"),
            ("艾吕尔", "技术自主性", "效率系统的自我扩张"),
        ],
        "hooks": {
            "cover": "技术不再为人服务，而是人为技术服务。",
            "video": "艾吕尔：技术已经自主，它只问“能不能”，从不问“应不应该”。",
            "social": "当“更高效”成为唯一答案时，真正该问的问题已经被静音了。",
        },
        "visual": "齿轮与数据流构成的巨大机器自动运转，人类被吸入其中成为润滑剂；色调铁灰与警示红。",
        "further": [
            "Ellul, J. *The Technological Society* (1964)",
            "Ellul, J. *The Technological System* (1980)",
        ],
    },
    {
        "theme": "数字劳动",
        "filename": "马克思-劳动异化.md",
        "id": "quote-marx-alienated-labor",
        "title": "劳动异化",
        "author": "卡尔·马克思 (Karl Marx)",
        "author_era": "1818–1883",
        "author_nationality": "德国",
        "domain": "社会学",
        "school": "classical-sociology",
        "era": "modern",
        "year": 1844,
        "original_language": "de",
        "tags": ["alienation", "labor", "capitalism", "数字劳动"],
        "mood": "炽烈",
        "cross_ref_id": "marx",
        "original": "The worker becomes all the poorer the more wealth he produces, the more his production increases in power and size.",
        "translation": "工人越是创造财富，他自己就越贫穷；他的生产在力量和规模上越是增长，他自己就越贫困。",
        "source": "Marx, *Economic and Philosophic Manuscripts of 1844*",
        "context": "马克思在1844年手稿中提出异化劳动四重维度：劳动者与劳动产品、劳动活动、类本质以及他人相异化。这一分析为后来的数字劳动批判提供了基础框架。",
        "interpretation": [
            ("产品与劳动者的分离", "工人生产得越多，产品越不属于自己。在数字平台中，用户生产数据，却不对数据拥有控制权。"),
            ("劳动过程的外在化", "劳动不再是自我实现的自由活动，而是被迫的、机械的、外在强加的活动。外卖骑手、内容审核员皆是明证。"),
            ("类本质的丧失", "人通过劳动改造世界、确证自身。当劳动被剥夺创造性，人也失去了成为“类存在”的可能。"),
        ],
        "genealogy": [
            ("黑格尔", "主奴辩证法", "劳动作为自我意识确证"),
            ("马克思", "异化劳动", "资本主义下的四重异化"),
            ("布雷弗曼", "去技能化", "资本对劳动过程的控制"),
        ],
        "hooks": {
            "cover": "你创造了一切，却什么都不拥有。",
            "video": "马克思 1844 年的警告：工人生产越多，自己越贫穷。数字时代依旧适用。",
            "social": "当你的劳动成果变成别人的资产，而你的疲惫只值一个评分，这就是异化。",
        },
        "visual": "无数双手在生产线上创造发光的产品，产品被传送带带向远方，工人留在阴影中；配色暗红与金属灰。",
        "further": [
            "Marx, K. *Economic and Philosophic Manuscripts of 1844*",
            "Marx, K. *Capital, Vol. 1* (1867)",
        ],
    },
    {
        "theme": "数字劳动",
        "filename": "布雷弗曼-去技能化.md",
        "id": "quote-braverman-deskilling",
        "title": "去技能化",
        "author": "哈里·布雷弗曼 (Harry Braverman)",
        "author_era": "1920–1976",
        "author_nationality": "美国",
        "domain": "社会学",
        "school": "labor-studies",
        "era": "contemporary",
        "year": 1974,
        "original_language": "en",
        "tags": ["deskilling", "labor-process", "capitalism", "数字劳动"],
        "mood": "沉重",
        "cross_ref_id": "harry-braverman",
        "original": "The separation of conception from execution, of head from hand, is the cardinal principle of scientific management.",
        "translation": "将构思与执行分离，将脑力与体力分离，是科学管理的核心原则。",
        "source": "Braverman, *Labor and Monopoly Capital* (1974)",
        "context": "布雷弗曼在《劳动与垄断资本》中分析泰勒制与科学管理：资本通过将计划与设计从工人手中剥离，使劳动碎片化、去技能化，从而加强对劳动过程的控制。",
        "interpretation": [
            ("概念与执行的分离", "当管理者掌握知识，工人只剩下重复动作。人工智能与算法管理将这一逻辑延伸到服务业与平台劳动。"),
            ("去技能化的目的", "去技能化不只是技术进步，更是权力策略：降低工人不可替代性，削弱议价能力，便于替换与压低工资。"),
            ("数字时代的延续", "平台通过算法分配任务、监控绩效、设定路径，把司机、骑手的“默会知识”转化为可管理的数据。"),
        ],
        "genealogy": [
            ("泰勒", "科学管理", "动作研究与标准化"),
            ("马克思", "异化劳动", "劳动与劳动者的分离"),
            ("布雷弗曼", "去技能化", "概念与执行的分离"),
        ],
        "hooks": {
            "cover": "把“思考”拿走，工作就变成了可替换的零件。",
            "video": "布雷弗曼：资本为什么要“去技能化”？因为无知的人更好控制。",
            "social": "当算法替你决定路线、节奏与评分，它夺走的不是自由，是你赖以立足的技能。",
        },
        "visual": "一只大脑被机械臂移走，留下的身体在流水线上重复动作；背景是数据面板；配色灰蓝与暗橙。",
        "further": [
            "Braverman, H. *Labor and Monopoly Capital* (1974)",
            "Taylor, F. W. *The Principles of Scientific Management* (1911)",
        ],
    },
    {
        "theme": "数字劳动",
        "filename": "格雷伯-狗屁工作.md",
        "id": "quote-graeber-bullshit-jobs",
        "title": "狗屁工作",
        "author": "大卫·格雷伯 (David Graeber)",
        "author_era": "1961–2020",
        "author_nationality": "美国",
        "domain": "社会学",
        "school": "labor-studies",
        "era": "contemporary",
        "year": 2013,
        "original_language": "en",
        "tags": ["bullshit-jobs", "meaningless-work", "digital-labor", "数字劳动"],
        "mood": "讽刺",
        "cross_ref_id": "david-graeber",
        "original": "Huge swathes of people, in Europe and North America in particular, spend their entire working lives performing tasks they secretly believe do not really need to be performed.",
        "translation": "尤其是在欧洲和北美，大量的人把整个工作生涯花在从事他们私下认为并不真正需要做的事情上。",
        "source": "Graeber, 'On the Phenomenon of Bullshit Jobs' (Strike! Magazine, 2013); later expanded in *Bullshit Jobs* (2018)",
        "context": "大卫·格雷伯在2013年的一篇文章中提出“狗屁工作”概念，引发全球讨论。他指出，许多现代工作缺乏社会价值，却被包装成有意义的存在，从事者深陷无意义感。",
        "interpretation": [
            ("无意义劳动的蔓延", "顾问、行政、公关、金融衍生品交易等岗位中，大量任务对社会并无实质贡献，却消耗大量人力与时间。"),
            ("制度性支配", "狗屁工作的存在不是因为经济需要，而是因为它维持了雇佣关系、阶层秩序与权力的表演。"),
            ("精神暴力", "从事明知无意义的工作会造成深层的心理伤害：虚假忙碌、自我怀疑与存在性空虚。"),
        ],
        "genealogy": [
            ("马克思", "异化劳动", "劳动与劳动者的分离"),
            ("凯恩斯", "技术性失业", "预测未来工作时长将大幅缩短"),
            ("格雷伯", "狗屁工作", "无意义劳动的制度化"),
        ],
        "hooks": {
            "cover": "如果这份工作消失，世界会变好吗？",
            "video": "格雷伯：很多人整个职业生涯，都在做一件自己知道没必要做的事。",
            "social": "当你说“这份工作其实没什么意义”，你不是懒，你是在说一个被压抑的真相。",
        },
        "visual": "一个人在摩天大楼隔间里整理永远整理不完的纸张，窗外是繁忙城市；色调 fluorescent 白与灰，讽刺而压抑。",
        "further": [
            "Graeber, D. *Bullshit Jobs: A Theory* (2018)",
            "Graeber, D. 'On the Phenomenon of Bullshit Jobs' (2013)",
        ],
    },
    {
        "theme": "算法权力",
        "filename": "肖沙娜-监控资本主义.md",
        "id": "quote-zuboff-surveillance-capitalism",
        "title": "监控资本主义",
        "author": "肖沙娜·祖博夫 (Shoshana Zuboff)",
        "author_era": "1951–",
        "author_nationality": "美国",
        "domain": "社会学",
        "school": "network-society",
        "era": "contemporary",
        "year": 2019,
        "original_language": "en",
        "tags": ["surveillance-capitalism", "data-extraction", "platform-power", "算法权力"],
        "mood": "冷峻",
        "cross_ref_id": "shoshana-zuboff",
        "original": "Surveillance capitalism unilaterally claims human experience as free raw material for translation into behavioral data.",
        "translation": "监控资本主义单方面宣称人类经验是免费的原材料，可转化为行为数据。",
        "source": "Zuboff, *The Age of Surveillance Capitalism* (2019)",
        "context": "肖沙娜·祖博夫在《监控资本主义时代》中提出，数字经济的本质不是服务用户，而是提取用户行为数据，预测并塑造行为，再将预测产品出售给广告商等买方。",
        "interpretation": [
            ("行为剩余", "用户使用服务时产生的数据远超服务本身所需。这些“行为剩余”被平台无偿占有，成为利润来源。"),
            ("预测产品", "监控资本主义的最终产品不是信息，而是对人类未来行为的预测。行为越可预测，权力越集中。"),
            ("经济逻辑与民主风险", "当私人公司掌握预测与塑造行为的权力，民主社会的自主性与公共空间受到威胁。"),
        ],
        "genealogy": [
            ("福柯", "规训权力", "通过监视塑造主体"),
            ("德勒兹", "控制社会", "连续调制而非封闭规训"),
            ("祖博夫", "监控资本主义", "数据提取与行为预测商品化"),
        ],
        "hooks": {
            "cover": "你不是用户，你是被开采的矿。",
            "video": "祖博夫：免费的 APP 为什么值钱？因为你的行为数据正在被出售。",
            "social": "“免费”是最贵的商业模式。它卖的不是产品，是对你未来的预测。",
        },
        "visual": "无数人的行为轨迹被抽取成发光的数据流，汇入平台巨塔；色调数据蓝与暗黑，冷峻而庞大。",
        "further": [
            "Zuboff, S. *The Age of Surveillance Capitalism* (2019)",
            "Turow, J. *The Daily You* (2011)",
        ],
    },
    {
        "theme": "算法权力",
        "filename": "帕斯奎尔-黑箱社会.md",
        "id": "quote-pasquale-black-box-society",
        "title": "黑箱社会",
        "author": "弗兰克·帕斯奎尔 (Frank Pasquale)",
        "author_era": "1974–",
        "author_nationality": "美国",
        "domain": "社会学",
        "school": "algorithmic-society",
        "era": "contemporary",
        "year": 2015,
        "original_language": "en",
        "tags": ["black-box", "algorithmic-accountability", "transparency", "算法权力"],
        "mood": "警醒",
        "cross_ref_id": "frank-pasquale",
        "original": "We are increasingly ruled by secret scoring systems, whose methods and effects are hidden from us.",
        "translation": "我们日益被秘密的评分系统所统治，其方法与影响对我们隐藏。",
        "source": "Pasquale, *The Black Box Society* (2015)",
        "context": "帕斯奎尔在《黑箱社会》中分析搜索引擎、金融、就业与医疗中的算法评分系统。这些系统以商业秘密为由拒绝透明，导致个人无法质疑、救济或理解影响自己命运的决策。",
        "interpretation": [
            ("三重黑箱", "搜索、评分与决策系统的不透明相互强化：我们不知道规则、不知道自己被如何归类、也无法挑战结果。"),
            ("权力不对等", "黑箱把知识垄断在平台与机构手中，个人处于信息不对称的弱势。问责机制被技术中立叙事架空。"),
            ("法律回应", "帕斯奎尔主张要求算法可解释、可审计，并建立公共机构监督关键领域的算法决策。"),
        ],
        "genealogy": [
            ("边沁", "全景监狱", "不可见的监视权力"),
            ("福柯", "规训与治理", "知识即权力"),
            ("帕斯奎尔", "黑箱社会", "算法不透明与法律问责"),
        ],
        "hooks": {
            "cover": "你被评分，却看不到分数。",
            "video": "帕斯奎尔：黑箱算法正在替你决定贷款、工作与搜索，而你一无所知。",
            "social": "当“算法这么说”成为免责金牌，正义就已经让位给了权力。",
        },
        "visual": "一个人面对巨大的黑色立方体，立方体表面闪烁着自己的评分与标签，但内部完全不可见；色调黑与警示黄。",
        "further": [
            "Pasquale, F. *The Black Box Society* (2015)",
            "Pasquale, F. *New Laws of Robotics* (2020)",
        ],
    },
    {
        "theme": "算法权力",
        "filename": "奥尼尔-数学杀伤性武器.md",
        "id": "quote-oneil-weapons-of-math-destruction",
        "title": "数学杀伤性武器",
        "author": "凯西·奥尼尔 (Cathy O'Neil)",
        "author_era": "1972–",
        "author_nationality": "美国",
        "domain": "社会学",
        "school": "algorithmic-society",
        "era": "contemporary",
        "year": 2016,
        "original_language": "en",
        "tags": ["algorithmic-bias", "fairness", "big-data", "算法权力"],
        "mood": "锐利",
        "cross_ref_id": "cathy-oneil",
        "original": "Models are opinions embedded in mathematics.",
        "translation": "模型就是嵌入数学中的观点。",
        "source": "O'Neil, *Weapons of Math Destruction* (2016)",
        "context": "凯西·奥尼尔在《数学杀伤性武器》中指出，大数据模型并非客观中立，而是嵌入设计者的目标、历史数据中的偏见与权力的运作。它们以“数学”之名放大不平等。",
        "interpretation": [
            ("模型的主观性", "选择目标变量、定义“成功”、收集数据，每一步都包含价值判断。模型不是发现真理，而是实现某种观点。"),
            ("规模化伤害", "当模型用于招聘、信贷、警务与司法时，偏见被系统化、规模化，受害者难以申诉。"),
            ("反馈循环", "模型不仅预测世界，还塑造世界。对贫困社区的预测性警务增加逮捕记录，反过来“证明”模型准确，形成歧视闭环。"),
        ],
        "genealogy": [
            ("帕斯奎尔", "黑箱社会", "算法不透明"),
            ("祖博夫", "监控资本主义", "数据提取"),
            ("奥尼尔", "数学杀伤性武器", "模型偏见与规模化伤害"),
        ],
        "hooks": {
            "cover": "数学不会说谎，但用数学的人会有偏见。",
            "video": "凯西·奥尼尔：每一个算法模型，都是一种观点穿上了数学的外衣。",
            "social": "别被“数据说话”唬住。数据会说你想让它说的话。",
        },
        "visual": "一把由公式与数字构成的枪，瞄准人群中的弱势群体；背景是数据流与监狱、银行图标；色调冷银与血红。",
        "further": [
            "O'Neil, C. *Weapons of Math Destruction* (2016)",
            "Benjamin, R. *Race After Technology* (2019)",
        ],
    },

    # -------------------------------------------------------------------------
    # Group 3
    # -------------------------------------------------------------------------
    {
        "theme": "身体感知",
        "filename": "梅洛-庞蒂-身体主体.md",
        "id": "quote-merleau-ponty-body-subject",
        "title": "身体主体",
        "author": "莫里斯·梅洛-庞蒂 (Maurice Merleau-Ponty)",
        "author_era": "1908–1961",
        "author_nationality": "法国",
        "domain": "哲学",
        "school": "phenomenology",
        "era": "contemporary",
        "year": 1945,
        "original_language": "fr",
        "tags": ["embodiment", "phenomenology", "body-subject", "身体感知"],
        "mood": "温润",
        "cross_ref_id": "merleau-ponty",
        "original": "Le corps est notre moyen d'avoir un monde.",
        "translation": "身体是我们拥有一个世界的方式。",
        "source": "Merleau-Ponty, *Phénoménologie de la perception* (1945)",
        "context": "梅洛-庞蒂在《知觉现象学》中反对笛卡尔式身心二元论。身体不是客观物体，而是“主体”：它既是感知者，又是被感知者；通过身体，世界向我们展开。",
        "interpretation": [
            ("身体不是机器", "身体不是由意识操控的客体，而是我们栖居世界、理解意义的媒介。没有身体，就没有“观点”与“视角”。"),
            ("身体图式", "身体空间不是几何空间，而是“我能”的场域。盲人的手杖、司机的汽车都可以成为身体图式的延伸。"),
            ("知觉的优先性", "知觉不是对感觉材料的被动接受，而是主动的、具身的、情境化的意义构成。"),
        ],
        "genealogy": [
            ("笛卡尔", "身心二元", "身体是被思维支配的机器"),
            ("胡塞尔", "生活世界", "知觉作为意义构成"),
            ("梅洛-庞蒂", "身体现象学", "身体是主体与世界的交汇"),
        ],
        "hooks": {
            "cover": "你不是住在身体里，你通过身体拥有世界。",
            "video": "梅洛-庞蒂：身体不是机器，而是我们感知世界的入口。",
            "social": "所谓“理性”，从来都不是一颗悬浮的大脑，而是一具会痛、会饿、会跳的身体的理性。",
        },
        "visual": "一双手伸向光，手的轮廓与世界边缘交融；配色温暖 flesh tone 与水彩蓝，温润而流动。",
        "further": [
            "Merleau-Ponty, M. *Phenomenology of Perception* (1945)",
            "Merleau-Ponty, M. *The Visible and the Invisible* (1964)",
        ],
    },
    {
        "theme": "身体感知",
        "filename": "斯卡里-疼痛的世界.md",
        "id": "quote-scarry-pain-world",
        "title": "疼痛的世界",
        "author": "伊莱恩·斯卡里 (Elaine Scarry)",
        "author_era": "1946–",
        "author_nationality": "美国",
        "domain": "哲学",
        "school": "political-philosophy",
        "era": "contemporary",
        "year": 1985,
        "original_language": "en",
        "tags": ["pain", "embodiment", "language", "body", "身体感知"],
        "mood": "沉痛",
        "cross_ref_id": "elaine-scarry",
        "original": "Physical pain does not simply resist language but actively destroys it, bringing about an immediate reversion to a state anterior to language, to the sounds and cries a person makes before language is learned.",
        "translation": "身体疼痛不仅抗拒语言，而且主动地摧毁语言，使人立即回到语言习得之前的状态，回到人在学会语言之前发出的声音与哭喊。",
        "source": "Scarry, *The Body in Pain* (1985)",
        "context": "斯卡里在《苦痛中的身体》中分析疼痛如何解构语言与世界。极度疼痛把个体从共享意义中抽离，造成一种无法被他人直接理解的孤独。",
        "interpretation": [
            ("疼痛的去世界化", "疼痛不仅是不适，它还摧毁对象、空间与时间。世界在剧痛中收缩，只剩下疼痛本身。"),
            ("表达的困境", "疼痛难以言表，不是因为词汇不够，而是因为疼痛抵抗对象化。这使得受害者的证词常被怀疑或淡化。"),
            ("政治暴力的根源", "酷刑与战争利用疼痛的去世界化力量，摧毁他人的现实感，从而瓦解其主体性与社会身份。"),
        ],
        "genealogy": [
            ("维特根斯坦", "私人语言论证", "疼痛语言的公共性"),
            ("梅洛-庞蒂", "身体现象学", "身体是意义场域"),
            ("斯卡里", "疼痛的政治哲学", "疼痛摧毁语言与世界"),
        ],
        "hooks": {
            "cover": "有些痛，不是找不到词，而是词被痛烧掉了。",
            "video": "斯卡里：剧烈疼痛会摧毁语言，让人退回哭喊。这也是为什么受害者最难被相信。",
            "social": "别再说“我理解你的痛”。真正的剧痛，是连“理解”这个词都无法抵达的地方。",
        },
        "visual": "一个人形轮廓在黑暗中张口呼喊，但声音化作碎片消散；配色深红与黑，沉痛而孤独。",
        "further": [
            "Scarry, E. *The Body in Pain* (1985)",
            "Scarry, E. *On Beauty and Being Just* (1999)",
        ],
    },
    {
        "theme": "身体感知",
        "filename": "扬-像女孩那样投掷.md",
        "id": "quote-young-throwing-like-a-girl",
        "title": "像女孩那样投掷",
        "author": "艾里斯·马里恩·扬 (Iris Marion Young)",
        "author_era": "1949–2006",
        "author_nationality": "美国",
        "domain": "哲学",
        "school": "feminist-philosophy",
        "era": "contemporary",
        "year": 1980,
        "original_language": "en",
        "tags": ["feminism", "embodiment", "gender", "body", "身体感知"],
        "mood": "锐利",
        "cross_ref_id": "iris-young",
        "original": "The young girl learns to keep her body small, contained, and closed, and this is reinforced by the clothing and activities considered appropriate for her.",
        "translation": "小女孩学会让自己的身体保持小巧、收敛与封闭，而这种训练通过被认为是适合她的服装与活动得到强化。",
        "source": "Young, *Throwing Like a Girl: A Phenomenology of Feminine Body Comportment, Motility and Spatiality* (1980)",
        "context": "扬在《像女孩那样投掷》中以现象学方法分析女性身体的运动方式。她指出，“像女孩那样投掷”不是生理差异的自然表达，而是性别规范在身体中的具身化结果。",
        "interpretation": [
            ("身体的性别规训", "女孩被鼓励收敛身体、避免扩张性动作；男孩则被鼓励占据空间。这些差异在童年游戏中被反复强化。"),
            ("能动性的限制", "女性身体常表现出“被约束的能动性”：同时朝向目标又抑制自己。这是一种存在性的矛盾。"),
            ("超越本质主义", "“像女孩”不是女性本质，而是社会规范的内化。改变它需要重新训练身体与空间的关系。"),
        ],
        "genealogy": [
            ("波伏娃", "第二性", "女性作为他者"),
            ("梅洛-庞蒂", "身体图式", "身体是意义构成"),
            ("扬", "女性主义现象学", "性别规范的身体具身化"),
        ],
        "hooks": {
            "cover": "“像女孩”不是天生的，是被教出来的。",
            "video": "艾里斯·扬：为什么女孩“不会”投掷？因为社会从小就训练她们收住身体。",
            "social": "你的身体不是自然产物，而是一部社会史。每一次“应该这样站、这样笑、这样坐”，都是规训。",
        },
        "visual": "一个女孩在操场上投掷，动作被虚线框住并逐渐缩小；旁边一个男孩的动作被放大；配色柔和的粉与锐利的蓝对比。",
        "further": [
            "Young, I. M. *Throwing Like a Girl* (1980)",
            "Young, I. M. *Justice and the Politics of Difference* (1990)",
        ],
    },
    {
        "theme": "情动",
        "filename": "斯宾诺莎-情动定义.md",
        "id": "quote-spinoza-affect",
        "title": "情动定义",
        "author": "巴鲁赫·斯宾诺莎 (Baruch Spinoza)",
        "author_era": "1632–1677",
        "author_nationality": "荷兰",
        "domain": "哲学",
        "school": "rationalism",
        "era": "early-modern",
        "year": 1677,
        "original_language": "la",
        "tags": ["affect", "conatus", "emotion", "ethics", "情动"],
        "mood": "澄明",
        "cross_ref_id": "spinoza",
        "original": "Affectus, quatenus ad corpus refertur, est ipsius corporis complexio, quatenus data est, et quatenus mentem in cogitandi actu ponit.",
        "translation": "情动，就其与身体相关而言，是身体的某种复合状态，藉此身体获得某种存在之力，同时使心灵具有某种思考之力。",
        "source": "Spinoza, *Ethica* (1677), Part III, Definition 3",
        "context": "斯宾诺莎在《伦理学》第三部分中重新定义情动：它不是灵魂对身体的被动反应，而是身体力量增减与心灵思想力量相应变化的统一过程。",
        "interpretation": [
            ("情动作为力量变化", "情动首先是身体“存在之力”（conatus）的增强或减弱，随后才被命名为主观的情绪（如快乐、悲伤）。"),
            ("身心一元", "斯宾诺莎反对笛卡尔身心二分。身体是情动的场所，但情动同时是心灵的观念；二者是同一实在的两个属性。"),
            ("理性与情感的统一", "理性不是压抑情感，而是理解情感的原因。理解情动即自由：从被动情感转向主动情感。"),
        ],
        "genealogy": [
            ("斯多葛派", "激情控制", "理性应当主宰情感"),
            ("笛卡尔", "激情论", "灵魂对身体的被动感知"),
            ("斯宾诺莎", "情动论", "力量增减与身心一元"),
        ],
        "hooks": {
            "cover": "情绪不是敌人，它是你存在之力的涨落。",
            "video": "斯宾诺莎：情动不是“感觉”，而是你的身体力量在变化。",
            "social": "别急着给情绪贴标签。先问：它让我的力量增加了，还是减少了？",
        },
        "visual": "一池水被不同力量扰动，涟漪大小代表力量增减；远处理性之光不是压制水，而是理解波纹；配色清澈蓝与金。",
        "further": [
            "Spinoza, B. *Ethics* (1677)",
            "Deleuze, G. *Spinoza: Practical Philosophy* (1970)",
        ],
    },
    {
        "theme": "情动",
        "filename": "德勒兹-情动是生成.md",
        "id": "quote-deleuze-affect-becoming",
        "title": "情动是生成",
        "author": "吉尔·德勒兹 (Gilles Deleuze)",
        "author_era": "1925–1995",
        "author_nationality": "法国",
        "domain": "哲学",
        "school": "post-structuralism",
        "era": "contemporary",
        "year": 1987,
        "original_language": "fr",
        "tags": ["affect", "becoming", "intensity", "body", "情动"],
        "mood": "流动",
        "cross_ref_id": "gilles-deleuze",
        "original": "Affect is the passage from one state to another, the duration of a state, or the increase and decrease of the power of acting.",
        "translation": "情动是从一个状态到另一个状态的过渡，是状态的绵延，也是行动力量增强或减弱的过程。",
        "source": "Deleuze, *Spinoza et la philosophie pratique* lectures; summarized in Deleuze & Guattari, *A Thousand Plateaus* (1980) and Massumi, *Parables for the Virtual* (2002)",
        "context": "德勒兹继承并转化斯宾诺莎的情动概念，将其发展为后结构主义核心范畴。情动不是被命名的主观情绪，而是身体在遭遇中力量增强或减弱的强度流变。",
        "interpretation": [
            ("情动先于情感", "“恐惧”“愤怒”是社会语言对情动的捕捉与固定。情动本身是前语言的强度变化，发生在主体化之前。"),
            ("生成而非存在", "情动指向“生成”（becoming）：身体与他者相遇时跨越自身边界，进入新的状态。"),
            ("反对心理个人主义", "情动不是个体心灵内部的事件，而是关系性、环境性、物质性的过程。"),
        ],
        "genealogy": [
            ("斯宾诺莎", "情动", "力量增减"),
            ("柏格森", "绵延", "时间作为流动"),
            ("德勒兹", "情动强度", "前语言的生成之流"),
        ],
        "hooks": {
            "cover": "你不是“有”情绪，你是在与他者相遇时不断生成。",
            "video": "德勒兹：情动不是情绪，而是力量变化的流动。",
            "social": "很多时候，我们急着给感受命名，却错过了它正在把我们带向哪里。",
        },
        "visual": "两股颜色不同的流体相遇，边界融合产生新的色彩与形态；背景是抽象的身体轮廓；配色霓虹渐变。",
        "further": [
            "Deleuze, G. *Spinoza: Practical Philosophy* (1970)",
            "Massumi, B. *Parables for the Virtual* (2002)",
        ],
    },
    {
        "theme": "情动",
        "filename": "艾哈迈德-情感的文化政治.md",
        "id": "quote-ahmed-cultural-politics-of-emotion",
        "title": "情感的文化政治",
        "author": "萨拉·艾哈迈德 (Sara Ahmed)",
        "author_era": "1969–",
        "author_nationality": "英国-澳大利亚",
        "domain": "社会学",
        "school": "gender-studies",
        "era": "contemporary",
        "year": 2004,
        "original_language": "en",
        "tags": ["affect", "emotion", "feminism", "culture", "情动"],
        "mood": "炽热",
        "cross_ref_id": "sara-ahmed",
        "original": "Emotions do things, and they align individuals with communities—or bodily space with social space—through the very intensity of their attachments.",
        "translation": "情感有所作为；正是通过其附着强度，情感使个体与共同体、身体空间与社会空间相互对齐。",
        "source": "Ahmed, *The Cultural Politics of Emotion* (2004)",
        "context": "艾哈迈德在《情感的文化政治》中挑战情感作为私人内在状态的传统观念。她认为情感在话语与制度中流通，建构“我们”与“他们”，并将特定身体标记为令人厌恶或恐惧的对象。",
        "interpretation": [
            ("情感的经济", "情感像物一样被生产、流通与归属。恐惧、爱、厌恶可以附着到种族、性别、宗教的他者身上，形成集体情绪。"),
            ("情感的指向性", "情感总是“关于”某物的。通过将恐惧指向移民、将厌恶指向特定身体，社会边界被情感反复绘制。"),
            ("女性主义的情感劳动", "“killy joy”因拒绝配合压迫性快乐脚本而被视为扫兴者。艾哈迈德将这种不适感转化为批判性的政治姿态。"),
        ],
        "genealogy": [
            ("斯宾诺莎", "情动", "力量变化"),
            ("德勒兹", "情动强度", "前个人流动"),
            ("艾哈迈德", "情感的文化政治", "情感的社会归属与边界建构"),
        ],
        "hooks": {
            "cover": "你的恐惧，可能是社会“借”给你的。",
            "video": "艾哈迈德：情感不是私人感受，它在社会中流通，并画出“我们”与“他们”。",
            "social": "当你对某个群体突然感到厌恶时，也许该问：这份厌恶是谁贴在我身上的？",
        },
        "visual": "无数情感标签像贴纸一样飞向不同身体，有的身体被贴上“危险”，有的被贴上“可爱”；配色饱和的情绪色块。",
        "further": [
            "Ahmed, S. *The Cultural Politics of Emotion* (2004)",
            "Ahmed, S. *The Promise of Happiness* (2010)",
        ],
    },
    {
        "theme": "疼痛脆弱",
        "filename": "巴特勒-脆弱性.md",
        "id": "quote-butler-vulnerability",
        "title": "脆弱性",
        "author": "朱迪斯·巴特勒 (Judith Butler)",
        "author_era": "1956–",
        "author_nationality": "美国",
        "domain": "社会学",
        "school": "gender-studies",
        "era": "contemporary",
        "year": 2004,
        "original_language": "en",
        "tags": ["vulnerability", "precarity", "grief", "ethics", "疼痛脆弱"],
        "mood": "悲悯",
        "cross_ref_id": "butler",
        "original": "Let's face it. We're undone by each other. And if we're not, we're missing something.",
        "translation": "面对现实吧。我们被彼此瓦解。如果不是这样，我们便错过了某种根本性的东西。",
        "source": "Butler, *Precarious Life: The Powers of Mourning and Violence* (2004)",
        "context": "巴特勒在《脆弱不安的生命》中反思“9·11”后的哀悼与暴力。她指出，人的存在本质上是脆弱的，正因为可被他人伤害，我们才彼此依赖、彼此负责。",
        "interpretation": [
            ("脆弱性的本体论", "脆弱不是偶然缺陷，而是人类存在的条件。身体是暴露的、依赖的、可毁灭的；这种脆弱性先于一切政治身份。"),
            ("哀悼的伦理", "哀悼让我们意识到失去他人就是失去自己的一部分。哀悼的公共性决定了哪些生命值得被承认、被哀悼。"),
            ("非暴力伦理", "承认他人的脆弱性，是反对暴力的伦理起点。暴力则源于将某些生命排除在“可哀悼”范围之外。"),
        ],
        "genealogy": [
            ("列维纳斯", "他者之脸", "对他人脆弱性的无限责任"),
            ("斯宾诺莎", "conatus", "保存自身存在的努力"),
            ("巴特勒", "脆弱性伦理", "从脆弱性出发的政治伦理"),
        ],
        "hooks": {
            "cover": "我们之所以需要彼此，是因为我们都能被彼此伤害。",
            "video": "巴特勒：脆弱不是弱点，而是我们彼此相连的根本原因。",
            "social": "承认自己会受伤，是理解他人伤口的开始。",
        },
        "visual": "两只手在虚空中相互触碰，指尖周围是脆弱的光线；配色柔和的金与灰，悲悯而温暖。",
        "further": [
            "Butler, J. *Precarious Life* (2004)",
            "Butler, J. *Frames of War* (2009)",
        ],
    },
    {
        "theme": "疼痛脆弱",
        "filename": "桑塔格-疾病的隐喻.md",
        "id": "quote-sontag-illness-metaphor",
        "title": "疾病的隐喻",
        "author": "苏珊·桑塔格 (Susan Sontag)",
        "author_era": "1933–2004",
        "author_nationality": "美国",
        "domain": "文学",
        "school": "essayists",
        "era": "contemporary",
        "year": 1978,
        "original_language": "en",
        "tags": ["illness", "metaphor", "pain", "culture", "疼痛脆弱"],
        "mood": "冷峻",
        "cross_ref_id": "susan-sontag",
        "original": "Illness is the night side of life, a more onerous citizenship. Everyone who is born holds dual citizenship, in the kingdom of the well and in the kingdom of the sick.",
        "translation": "疾病是生命的暗夜面，一种更沉重的公民身份。每个出生的人都拥有双重国籍：健康王国与疾病王国。",
        "source": "Sontag, *Illness as Metaphor* (1978)",
        "context": "桑塔格在《疾病的隐喻》中批判将疾病道德化的文化：癌症被看作压抑的果实，结核病被视为艺术家的浪漫病。这些隐喻加重患者羞耻，遮蔽疾病的真实经验。",
        "interpretation": [
            ("疾病的隐喻暴力", "“战斗”“胜利”“放弃”等军事隐喻把疾病变成个人品格的考验。患者不仅承受身体痛苦，还要承受道德叙事。"),
            ("双重王国", "健康与疾病不是遥远两极，而是每个人随时可能跨越的边界。承认这一点，是对患者最基本的共情。"),
            ("反对浪漫化与污名化", "桑塔格呼吁剥除疾病的隐喻，直面疾病的生物学与社会现实。清晰的认知本身就是一种解放。"),
        ],
        "genealogy": [
            ("尼采", "道德化的身体", "疾病作为道德失败"),
            ("福柯", "医学凝视", "权力对身体的建构"),
            ("桑塔格", "疾病的隐喻", "文化叙事如何加重痛苦"),
        ],
        "hooks": {
            "cover": "每个活着的人，都持健康与疾病的双重护照。",
            "video": "桑塔格：癌症不是“压抑”的惩罚，疾病首先是一场身体事件，而不是道德考验。",
            "social": "别把疾病说成一场战争。患者不需要“战败”的羞辱，他们需要被理解的身体与真实。",
        },
        "visual": "一本护照被撕成两半，一半是明亮的健康王国，一半是暗夜的疾病王国，中间是模糊的人影；配色冷暖对比。",
        "further": [
            "Sontag, S. *Illness as Metaphor* (1978)",
            "Sontag, S. *AIDS and Its Metaphors* (1989)",
        ],
    },
    {
        "theme": "疼痛脆弱",
        "filename": "列维纳斯-他者之脸.md",
        "id": "quote-levinas-face-of-the-other",
        "title": "他者之脸",
        "author": "伊曼努尔·列维纳斯 (Emmanuel Levinas)",
        "author_era": "1906–1995",
        "author_nationality": "立陶宛-法国",
        "domain": "哲学",
        "school": "phenomenology",
        "era": "contemporary",
        "year": 1961,
        "original_language": "fr",
        "tags": ["alterity", "face", "ethics", "vulnerability", "疼痛脆弱"],
        "mood": "庄严",
        "cross_ref_id": "emmanuel-levinas",
        "original": "The face is what one cannot kill, or at least it is that whose meaning consists in saying: thou shalt not kill.",
        "translation": "脸是人所不能杀死的，或者至少可以说，脸的意义就在于说：你不可杀人。",
        "source": "Levinas, *Totality and Infinity* (1961)",
        "context": "列维纳斯在《总体与无限》中提出，面对面相遇时，他者的脸同时呈现脆弱与权威。它不通过论证命令我，而是以裸露的面容发出伦理召唤。",
        "interpretation": [
            ("脸作为伦理事件", "脸不是生理器官，而是他者不可被还原为“同一”的痕迹。它打破我对世界的总体化把握。"),
            ("脆弱性的命令", "脸的裸露——眼睛、皮肤、表情——既是易受伤害的标志，也是“不可杀人”的原始律令。"),
            ("伦理先于存在论", "传统哲学追问“存在是什么”，列维纳斯追问“我对他者负有什么责任”。伦理成为第一哲学。"),
        ],
        "genealogy": [
            ("康德", "定言命令", "理性颁布普遍道德法则"),
            ("海德格尔", "此在", "存在论优先"),
            ("列维纳斯", "他者之脸", "伦理先于存在论"),
        ],
        "hooks": {
            "cover": "看见一张脸，就是接受一个不可杀死的命令。",
            "video": "列维纳斯：他者的脸对你说“不可杀人”。伦理从面对面的脆弱开始。",
            "social": "当灾难中的面孔变成数字，我们就已经远离了伦理。重新看见脸，是重新负起责任。",
        },
        "visual": "一张极度简化的人脸从黑暗中浮现，双眼注视观者，周围是微弱的光晕；配色暗黑与圣洁白。",
        "further": [
            "Levinas, E. *Totality and Infinity* (1961)",
            "Levinas, E. *Ethics and Infinity* (1982)",
        ],
    },
    # -------------------------------------------------------------------------
    # Group 4
    # -------------------------------------------------------------------------
    {
        "theme": "生态危机",
        "filename": "卡森-寂静的春天.md",
        "id": "quote-carson-silent-spring",
        "title": "寂静的春天",
        "author": "蕾切尔·卡森 (Rachel Carson)",
        "author_era": "1907–1964",
        "author_nationality": "美国",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "year": 1962,
        "original_language": "en",
        "tags": ["ecology", "pesticides", "silent-spring", "environmentalism", "生态危机"],
        "mood": "哀婉",
        "cross_ref_id": "rachel-carson",
        "original": "Over increasingly large areas of the United States, spring now comes unheralded by the return of birds, and the early mornings are strangely silent where once they were filled with beauty.",
        "translation": "在美国越来越多的地区，春天降临了，却不再有鸟儿的回归来宣告；清晨出奇地寂静，而曾经那里充满了美。",
        "source": "Carson, *Silent Spring* (1962)",
        "context": "蕾切尔·卡森在《寂静的春天》中揭示 DDT 等化学农药如何通过食物链毒害鸟类、鱼类与人类。她打破了“化学控制自然”的进步叙事，开启了现代环境运动。",
        "interpretation": [
            ("生态系统的连锁反应", "杀虫剂不只杀死目标害虫，也杀死传粉昆虫、鸟类与土壤微生物。生态是一个相互依存的网络，而非可线性控制的机器。"),
            ("科学传播的伦理", "卡森以文学性的科学写作向公众传达风险，证明科学家有责任让知识进入公共领域，而非仅服务于产业。"),
            ("自然的内在价值", "鸟儿的歌声不仅是资源或景观，而是生命共同体的一部分。它的消失是世界的贬值。"),
        ],
        "genealogy": [
            ("达尔文", "生态相互依存", "生命网络"),
            ("利奥波德", "土地伦理", "道德共同体扩展至自然"),
            ("卡森", "环境运动", "化学污染公共化"),
        ],
        "hooks": {
            "cover": "如果春天不再被鸟鸣唤醒，我们失去了什么？",
            "video": "1962 年，卡森写下《寂静的春天》，让全世界听见消失的鸟鸣。",
            "social": "每一只消失的鸟，都是生态系统给我们的一张欠条。",
        },
        "visual": "一片春天的田野，树木开花，但没有鸟；空中只有农药喷洒机的剪影；配色明亮的春绿与死灰对比。",
        "further": [
            "Carson, R. *Silent Spring* (1962)",
            "Lear, L. *Rachel Carson: Witness for Nature* (1997)",
        ],
    },
    {
        "theme": "生态危机",
        "filename": "利奥波德-土地伦理.md",
        "id": "quote-leopold-land-ethic",
        "title": "土地伦理",
        "author": "奥尔多·利奥波德 (Aldo Leopold)",
        "author_era": "1887–1948",
        "author_nationality": "美国",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "modern",
        "year": 1949,
        "original_language": "en",
        "tags": ["land-ethic", "conservation", "ecology", "生态危机"],
        "mood": "厚重",
        "cross_ref_id": "aldo-leopold",
        "original": "A thing is right when it tends to preserve the integrity, stability, and beauty of the biotic community. It is wrong when it tends otherwise.",
        "translation": "当一件事倾向于保护生物共同体的完整、稳定与美丽时，它就是对的；反之则是错的。",
        "source": "Leopold, *A Sand County Almanac* (1949)",
        "context": "利奥波德在《沙乡年鉴》中提出“土地伦理”，主张把道德关怀从人类共同体扩展到土壤、水、植物与动物。这是对以经济效用为中心的自然观的根本挑战。",
        "interpretation": [
            ("共同体边界的扩展", "伦理演化的历史是道德共同体不断扩大的过程。利奥波德认为，下一步应包括整个生物共同体。"),
            ("完整、稳定与美丽", "土地伦理的判准不是人类的短期利益，而是生态系统的长期健康。这三者相互关联，无法被还原为经济指标。"),
            ("从征服者到共同体成员", "人类应放弃作为自然征服者的角色，转而视自己为土地共同体中的普通成员与公民。"),
        ],
        "genealogy": [
            ("达尔文", "同情扩展", "道德情感的演化"),
            ("缪尔", "荒野保护", "自然的内在价值"),
            ("利奥波德", "土地伦理", "生物共同体的完整性"),
        ],
        "hooks": {
            "cover": "当好与坏的标准，不再只问对人有没有用。",
            "video": "利奥波德：把道德共同体从人类扩展到土地，是伦理的下一步进化。",
            "social": "别只问“这能卖多少钱”。问问：它是否让土地更完整、更美丽？",
        },
        "visual": "一只手握着土壤，土壤中是根系、昆虫、种子与微生物的微缩世界；配色大地棕与生命绿。",
        "further": [
            "Leopold, A. *A Sand County Almanac* (1949)",
            "Callicott, J. B. *In Defense of the Land Ethic* (1989)",
        ],
    },
    {
        "theme": "生态危机",
        "filename": "洛夫洛克-盖亚假说.md",
        "id": "quote-lovelock-gaia",
        "title": "盖亚假说",
        "author": "詹姆斯·洛夫洛克 (James Lovelock)",
        "author_era": "1919–2022",
        "author_nationality": "英国",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "year": 1979,
        "original_language": "en",
        "tags": ["gaia", "earth-systems", "planetary-science", "生态危机"],
        "mood": "敬畏",
        "cross_ref_id": "james-lovelock",
        "original": "The entire range of living matter on Earth, from whales to viruses, and from oaks to algae, could be regarded as constituting a single living entity, capable of manipulating the Earth's atmosphere to suit its overall needs.",
        "translation": "地球上从鲸鱼到病毒、从橡树到藻类的全部生命物质，可以被看作构成一个单一的活体，能够调节地球大气以满足其整体需求。",
        "source": "Lovelock, *Gaia: A New Look at Life on Earth* (1979)",
        "context": "洛夫洛克与微生物学家林恩·马古利斯共同提出盖亚假说，认为地球是一个自我调节的生命系统。生物圈、大气、海洋与地质过程相互作用，维持适合生命的环境。",
        "interpretation": [
            ("行星层面的有机整体", "地球不只是生命栖息的物理场所，而是生命与环境共同演化的动态系统。大气成分、温度与化学状态被生命活动调节。"),
            ("自我调节与临界点", "盖亚系统能在一定范围内自我修复，但人类活动可能触发不可逆的临界点，破坏这种平衡。"),
            ("从机械地球到生命地球", "盖亚假说挑战了将自然视为被动资源的机械世界观，为生态伦理与行星思维提供了科学意象。"),
        ],
        "genealogy": [
            ("古希腊", "盖亚神话", "大地女神"),
            ("达尔文", "共同演化", "物种相互塑造环境"),
            ("洛夫洛克", "盖亚假说", "地球作为自我调节系统"),
        ],
        "hooks": {
            "cover": "地球不是石头，而是一个巨大的生命体。",
            "video": "洛夫洛克：地球会自我调节，但人类的破坏可能突破它的临界点。",
            "social": "当你说“保护环境”，也许更该说“保护我们共同的生命系统”。",
        },
        "visual": "地球被细密的绿色脉络与蓝色洋流包裹，像一颗跳动的心脏；配色深蓝与翠绿，庄严而生机勃勃。",
        "further": [
            "Lovelock, J. *Gaia: A New Look at Life on Earth* (1979)",
            "Lovelock, J. *The Revenge of Gaia* (2006)",
        ],
    },
    {
        "theme": "深层生态",
        "filename": "内斯-深层生态学.md",
        "id": "quote-naess-deep-ecology",
        "title": "深层生态学",
        "author": "阿恩·内斯 (Arne Næss)",
        "author_era": "1912–2009",
        "author_nationality": "挪威",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "year": 1973,
        "original_language": "en",
        "tags": ["deep-ecology", "ecosophy", "self-realization", "深层生态"],
        "mood": "辽阔",
        "cross_ref_id": "arne-naess",
        "original": "The flourishing of human and non-human life on Earth has intrinsic value. The value of non-human life-forms is independent of the usefulness these may have for narrow human purposes.",
        "translation": "地球上人类与非人类生命的繁荣具有内在价值。非生命形式的价值不依赖于它们对狭隘人类目的的用处。",
        "source": "Næss, 'The Shallow and the Deep, Long-Range Ecology Movement' (1973)",
        "context": "内斯在1973年区分“浅层生态运动”（关注污染与资源）与“深层生态运动”（追问人类中心主义本身）。深层生态学主张扩展自我认同，将生态系统纳入道德关怀。",
        "interpretation": [
            ("浅层与深层", "浅层生态学把自然问题化约为人类福利问题；深层生态学则认为人类中心主义本身就是问题，主张生态系统的内在价值。"),
            ("生态自我", "自我实现不是个人成功，而是“大我”的扩展：从个体到人类、到物种、再到生态系统。"),
            ("多样性与共生", "生物多样性本身具有价值。人类应减少人口与消费，给其他生命留下生存空间。"),
        ],
        "genealogy": [
            ("斯宾诺莎", "自然即神", "人类是自然的一部分"),
            ("利奥波德", "土地伦理", "生物共同体的道德地位"),
            ("内斯", "深层生态学", "扩展自我与内在价值"),
        ],
        "hooks": {
            "cover": "真正的自我，比“我”大得多。",
            "video": "内斯：深层生态学问你——你的自我，能不能扩展到整个生态系统？",
            "social": "别再说“保护自然是为了人类”。自然首先是它自己，我们只是其中一员。",
        },
        "visual": "一个人形轮廓逐渐融入山脉、森林与河流，边界消融；配色大地绿与天空蓝，辽阔而宁静。",
        "further": [
            "Næss, A. *Ecology, Community and Lifestyle* (1989)",
            "Sessions, G. (ed.) *Deep Ecology for the Twenty-First Century* (1995)",
        ],
    },
    {
        "theme": "深层生态",
        "filename": "布克钦-社会生态学.md",
        "id": "quote-bookchin-social-ecology",
        "title": "社会生态学",
        "author": "默里·布克钦 (Murray Bookchin)",
        "author_era": "1921–2006",
        "author_nationality": "美国",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "year": 1982,
        "original_language": "en",
        "tags": ["social-ecology", "libertarian-municipalism", "hierarchy", "深层生态"],
        "mood": "炽烈",
        "cross_ref_id": "murray-bookchin",
        "original": "The very notion of the domination of nature by man stems from the very real domination of human by human.",
        "translation": "人统治自然这一观念本身，就源于人对人的真实统治。",
        "source": "Bookchin, *The Ecology of Freedom* (1982)",
        "context": "布克钦在《自由的生态学》中提出社会生态学。他认为生态危机不是抽象的人口或技术问题，而是社会等级制、阶级统治与商品化的结果；人对自然的支配复制了人对人的支配。",
        "interpretation": [
            ("统治的连锁", "父权制、阶级、国家、种族主义与生态破坏共享同一套逻辑：将一部分存在贬低为可被支配的他者。"),
            ("去中心化的直接民主", "布克钦提出“自由市镇主义”，主张通过地方自治、直接民主与面对面审议重建生态社会。"),
            ("反对神秘化自然", "与深层生态学的某些神秘化倾向不同，布克钦坚持社会分析：生态问题必须通过改变社会结构来解决。"),
        ],
        "genealogy": [
            ("马克思", "历史唯物主义", "社会结构决定意识"),
            ("克鲁泡特金", "互助论", "无政府主义与自然秩序"),
            ("布克钦", "社会生态学", "生态危机源于社会统治"),
        ],
        "hooks": {
            "cover": "人对自然的统治，始于人对人的统治。",
            "video": "布克钦：不解决社会等级制，就无法解决生态危机。",
            "social": "当你说“人类要保护地球”，先问：是谁在“代表”人类统治？",
        },
        "visual": "一座金字塔，顶层是人统治自然，底层是人统治人；底层断裂，上层随之崩塌；配色暗红与土黄。",
        "further": [
            "Bookchin, M. *The Ecology of Freedom* (1982)",
            "Bookchin, M. *Post-Scarcity Anarchism* (1971)",
        ],
    },
    {
        "theme": "深层生态",
        "filename": "普拉姆伍德-理性的主宰.md",
        "id": "quote-plumwood-mastery-of-nature",
        "title": "理性的主宰",
        "author": "瓦尔·普拉姆伍德 (Val Plumwood)",
        "author_era": "1939–2008",
        "author_nationality": "澳大利亚",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "year": 1993,
        "original_language": "en",
        "tags": ["ecofeminism", "reason", "mastery", "nature", "深层生态"],
        "mood": "锐利",
        "cross_ref_id": "val-plumwood",
        "original": "Rationalism is not just an intellectual error, but a whole form of life, a whole problematic construction of selfhood and otherness.",
        "translation": "理性主义不仅是一种智识错误，而是一种完整的生活方式，一种关于自我与他者的成问题的整体建构。",
        "source": "Plumwood, *Feminism and the Mastery of Nature* (1993)",
        "context": "普拉姆伍德在《女性主义与对自然的主宰》中批判西方理性主义传统。她认为理性/自然、男性/女性、文明/野蛮、心灵/身体等二元论共同为生态破坏与压迫辩护。",
        "interpretation": [
            ("二元论的统治逻辑", "西方理性传统将理性等同于人类（尤其白人男性），把自然、女性、有色人种贬为低等的“他者”。这种逻辑合法化了对一切的统治。"),
            ("生态女性主义", "对自然的支配与对女性的支配共享同一套框架：将对象视为资源、财产与工具。"),
            ("关系性自我", "普拉姆伍德主张一种嵌入自然与社会关系中的自我。生态伦理应基于相互依存，而非自主理性主体的支配。"),
        ],
        "genealogy": [
            ("波伏娃", "第二性", "女性作为他者"),
            ("利奥波德", "土地伦理", "扩展道德共同体"),
            ("普拉姆伍德", "生态女性主义", "批判理性主义二元论"),
        ],
        "hooks": {
            "cover": "理性主义不只是错了，它是一种生活方式的统治。",
            "video": "普拉姆伍德：为什么征服自然和压迫女性用的是同一套逻辑？",
            "social": "当我们把“理性”当作统治的通行证时，自然、身体、情感都成了被征服的他者。",
        },
        "visual": "一把标有“理性”的剑劈开自然、女性与身体的形象；裂缝中涌出绿色的反抗藤蔓；配色冷银与深绿。",
        "further": [
            "Plumwood, V. *Feminism and the Mastery of Nature* (1993)",
            "Plumwood, V. *Environmental Culture* (2002)",
        ],
    },
    {
        "theme": "人类世",
        "filename": "拉图尔-我们从未现代过.md",
        "id": "quote-latour-never-modern",
        "title": "我们从未现代过",
        "author": "布鲁诺·拉图尔 (Bruno Latour)",
        "author_era": "1947–2022",
        "author_nationality": "法国",
        "domain": "社会学",
        "school": "actor-network",
        "era": "contemporary",
        "year": 1991,
        "original_language": "fr",
        "tags": ["actor-network", "modernity", "nature-culture", "人类世"],
        "mood": "机敏",
        "cross_ref_id": "latour",
        "original": "We have never been modern.",
        "translation": "我们从未现代过。",
        "source": "Latour, *Nous n'avons jamais été modernes* (1991)",
        "context": "拉图尔在《我们从未现代过》中批判现代性的“纯化工作”——将自然与文化、主体与客体、事实与价值截然分离。他指出，现代科学与技术实践实际上不断制造“杂合体”，却假装世界已被 purification。",
        "interpretation": [
            ("纯化与转义", "现代社会一边进行“纯化”（区分自然/社会），一边不断生产“杂合体”（气候、转基因、AI）。这种矛盾是现代性的根本张力。"),
            ("非人类行动者", "自然物、技术物、微生物并非被动背景，而是行动者网络中的行动者。它们参与塑造社会，也受社会影响。"),
            ("人类世的本体论", "气候危机证明自然与社会无法分离。拉图尔的理论为人类世政治提供了基础：我们必须公开承认并民主地协商这些杂合体。"),
        ],
        "genealogy": [
            ("笛卡尔", "主客二分", "现代性的认识论基础"),
            ("福柯", "权力/知识", "科学作为权力实践"),
            ("拉图尔", "行动者网络理论", "人与非人类的共同行动"),
        ],
        "hooks": {
            "cover": "自然与社会的墙，从来就没真正存在过。",
            "video": "拉图尔：我们从未现代过。自然和文化，其实一直纠缠在一起。",
            "social": "别再说“这是科学问题，不是政治问题”。在气候危机里，它们从一开始就是同一件事。",
        },
        "visual": "一面标着“自然/文化”的玻璃墙被打破，碎片中飞出病毒、芯片、河流与选票；配色现代冷白与复杂多彩。",
        "further": [
            "Latour, B. *We Have Never Been Modern* (1991)",
            "Latour, B. *Facing Gaia* (2017)",
        ],
    },
    {
        "theme": "人类世",
        "filename": "莫顿-超对象.md",
        "id": "quote-morton-hyperobjects",
        "title": "超对象",
        "author": "蒂莫西·莫顿 (Timothy Morton)",
        "author_era": "1968–",
        "author_nationality": "英国-美国",
        "domain": "哲学",
        "school": "environmental-philosophy",
        "era": "contemporary",
        "year": 2013,
        "original_language": "en",
        "tags": ["hyperobjects", "anthropocene", "ecology", "climate", "人类世"],
        "mood": "怪诞",
        "cross_ref_id": "timothy-morton",
        "original": "A hyperobject is an object that is massively distributed in time and space relative to humans.",
        "translation": "超对象是在时间和空间上相对于人类而言大规模分布的对象。",
        "source": "Morton, *Hyperobjects: Philosophy and Ecology after the End of the World* (2013)",
        "context": "莫顿在《超对象》中提出，气候变化、塑料污染、核辐射等是巨大的存在物，它们跨越时空、无法被直接把握，却渗透在日常生活中。它们挑战了传统的主客二分与审美距离。",
        "interpretation": [
            ("不可见的实在", "超对象太大、太分散，无法被整体感知。我们无法“看到”气候变化，只能通过极端天气、冰川消融等局部征候体验它。"),
            ("怪诞的亲密关系", "超对象让我们与自然不再是审美距离外的风景，而是纠缠在呼吸、饮食、购物中的怪诞亲密。"),
            ("人类世的时空感", "人类世意味着自然已不存在：没有一个“外部自然”可供逃避。我们必须学习与超对象共存，而非期待回到前工业田园。"),
        ],
        "genealogy": [
            ("洛夫洛克", "盖亚假说", "行星尺度的生命系统"),
            ("拉图尔", "行动者网络", "人与非人类的共同行动"),
            ("莫顿", "超对象", "人类世的存在物"),
        ],
        "hooks": {
            "cover": "气候变化不是“环境问题”，而是一个你看不见却无处不在的巨大存在。",
            "video": "莫顿：超对象太大，我们无法看见它，但它正在重塑我们的生活。",
            "social": "别等“看见”气候危机才行动。它早已在你呼吸的空气、买的快递、经历的极端天气里。",
        },
        "visual": "一个巨大而模糊的存在物笼罩城市，只有局部触须可见；人们在其中照常生活；配色怪诞的紫外与灰绿。",
        "further": [
            "Morton, T. *Hyperobjects* (2013)",
            "Morton, T. *Dark Ecology* (2016)",
        ],
    },
    {
        "theme": "人类世",
        "filename": "哈拉维-与麻烦共存.md",
        "id": "quote-haraway-staying-with-the-trouble",
        "title": "与麻烦共存",
        "author": "唐娜·哈拉维 (Donna Haraway)",
        "author_era": "1944–",
        "author_nationality": "美国",
        "domain": "社会学",
        "school": "gender-studies",
        "era": "contemporary",
        "year": 2016,
        "original_language": "en",
        "tags": ["anthropocene", "multispecies", "feminism", "ecology", "人类世"],
        "mood": "坚韧",
        "cross_ref_id": "haraway",
        "original": "It matters what stories make worlds, what worlds make stories. Staying with the trouble requires making oddkin; that is, making unexpected collaborations and combinations across kinds.",
        "translation": "什么故事造就世界，什么世界造就故事，这很重要。与麻烦共存需要制造“怪亲”——即跨物种、跨类别的意外合作与组合。",
        "source": "Haraway, *Staying with the Trouble: Making Kin in the Chthulucene* (2016)",
        "context": "哈拉维在《与麻烦共存》中拒绝“人类世”的救赎叙事与末日叙事。她提出“克苏鲁纪”（Chthulucene），强调人类必须与其他物种建立“怪亲”关系，在废墟中共同创造可生存的未来。",
        "interpretation": [
            ("故事即世界", "我们讲述的世界观决定了我们如何行动。人类中心主义与末日叙事都需要被更具关系性的故事取代。"),
            ("怪亲", "“亲缘”不应仅限于血缘或物种。人与微生物、植物、机器、他人都可以在困境中结成意想不到的联盟。"),
            ("行动主义的多物种转向", "生态政治不是拯救地球，而是学习与其他生命共同在受损星球上生活、修复与创造。"),
        ],
        "genealogy": [
            ("利奥波德", "土地伦理", "生物共同体"),
            ("拉图尔", "行动者网络", "人与非人类共同行动"),
            ("哈拉维", "克苏鲁纪", "多物种怪亲与麻烦共存"),
        ],
        "hooks": {
            "cover": "别逃了。学会与麻烦共存，才是这个时代最硬的智慧。",
            "video": "哈拉维：人类世没有救世主，我们只能与其他生命结成“怪亲”，一起修船。",
            "social": "与其幻想回到田园，不如在废墟里和意想不到的伙伴一起，把未来拼出来。",
        },
        "visual": "多种生物与人类的手共同编织一张破网：昆虫、根系、电缆与手指交错；配色废土橙与再生绿。",
        "further": [
            "Haraway, D. *Staying with the Trouble* (2016)",
            "Haraway, D. *The Companion Species Manifesto* (2003)",
        ],
    },
]
